Repository NASA-LIS/LISF, pull requests merged in 2019-10, with the labels that each got.

#365 Fix critical and high issues from Fortify Audit scan
  ldt/lib/xmrg/xmrg_read_data_c.c
  ldt/lib/xmrg/xmrg_read_header_c.c
  lis/core/LIS_create_subdirs.c
  lis/core/LIS_memory_managementC.c
  lis/core/xmrg_read_data_c.c
  lis/core/xmrg_read_header_c.c
Labels: BugFix

#223 Improve LDT log messages for HyMAP restart files
  ldt/core/LDT_ensRstMod.F90
Labels: BugFix

#360 Update file name for APHRODITE product for 2007-2015
  lvt/datastreams/APHRO_PRCP/readAPHROPRCPObs.F90
Labels: BugFix

#245 Fix/dateline
  ldt/core/LDT_domainMod.F90
  ldt/core/LDT_fileIOMod.F90
  ldt/core/LDT_gridmappingMod.F90
  ldt/core/LDT_paramProcMod.F90
  ldt/domains/gaussian/readinput_gaussian.F90
  ldt/domains/latlon/readinput_latlon.F90
  ldt/params/landcover/read_MODISNative_lc.F90
  ldt/params/mask/create_maskfile.F90
  lis/testcases/domains/latlon_idlcross/MODEL_OUTPUT_LIST.TBL
  lis/testcases/domains/latlon_idlcross/README
  lis/testcases/domains/latlon_idlcross/input.ctl
  lis/testcases/domains/latlon_idlcross/input_testcase.ctl
  lis/testcases/domains/latlon_idlcross/ldt.config
  lis/testcases/domains/latlon_idlcross/lis.config
  lis/testcases/domains/latlon_idlcross/output.ctl
  lis/testcases/domains/latlon_idlcross/testcase.ctl
Labels: BugFix

#364 Allows ensemble averaging of LIS ensemble outputs
  lvt/core/LVT_LISoutputHandlerMod.F90
Labels: BugFix

#217 Fix HyMAP/HyMAP-2 documentation and make codes more consistent
  ldt/configs/ldt.config_master
  ldt/params/HYMAP/HYMAP_parmsMod.F90
  ldt/params/HYMAP/read_HYMAP_baseflow_delay.F90
  ldt/params/HYMAP/read_HYMAP_baseflow_dwi_ratio.F90
  ldt/params/HYMAP/read_HYMAP_basin.F90
  ldt/params/HYMAP/read_HYMAP_basin_mask.F90
  ldt/params/HYMAP/read_HYMAP_drain_area.F90
  ldt/params/HYMAP/read_HYMAP_fld_height.F90
  ldt/params/HYMAP/read_HYMAP_fld_z.F90
  ldt/params/HYMAP/read_HYMAP_flow_dir_x.F90
  ldt/params/HYMAP/read_HYMAP_flow_dir_y.F90
  ldt/params/HYMAP/read_HYMAP_flow_type.F90
  ldt/params/HYMAP/read_HYMAP_grid_area.F90
  ldt/params/HYMAP/read_HYMAP_grid_dist.F90
  ldt/params/HYMAP/read_HYMAP_grid_elev.F90
  ldt/params/HYMAP/read_HYMAP_refq.F90
  ldt/params/HYMAP/read_HYMAP_river_height.F90
  ldt/params/HYMAP/read_HYMAP_river_length.F90
  ldt/params/HYMAP/read_HYMAP_river_width.F90
  ldt/params/HYMAP/read_HYMAP_river_z.F90
  ldt/params/HYMAP/read_HYMAP_runoff_delay.F90
  ldt/params/HYMAP/read_HYMAP_runoff_delaym.F90
  ldt/params/HYMAP/read_HYMAP_runoff_dwi_ratio.F90
  lis/configs/MODEL_OUTPUT_LIST.TBL.adoc
  lis/configs/lis.config.adoc
  lis/routing/HYMAP2_router/HYMAP2_model_core.F90
  lis/routing/HYMAP2_router/HYMAP2_routingMod.F90
  lis/routing/HYMAP2_router/HYMAP2_routing_writerst.F90
  lvt/core/LVT_LISoutputHandlerMod.F90
  lvt/core/LVT_histDataMod.F90
Labels: BugFix, LowPriority

#372 Update LIS config documentation for MERRA2 reader
  lis/configs/lis.config.adoc
Labels: Documentation

#373 Fix low severity issues from Fortify Audit scan
  ldt/core/LDT_ANNdata_FTable.c
  ldt/core/LDT_DAobs_FTable.c
  ldt/core/LDT_LSMparams_FTable.c
  ldt/core/LDT_albedo_FTable.c
  ldt/core/LDT_climparms_FTable.c
  ldt/core/LDT_domain_FTable.c
  ldt/core/LDT_gfrac_FTable.c
  ldt/core/LDT_glacier_FTable.c
  ldt/core/LDT_laisai_FTable.c
  ldt/core/LDT_lakeparams_FTable.c
  ldt/core/LDT_landcover_FTable.c
  ldt/core/LDT_mask_FTable.c
  ldt/core/LDT_metforcdscale_FTable.c
  ldt/core/LDT_metforcing_FTable.c
  ldt/core/LDT_noahparms_FTable.c
  ldt/core/LDT_routingparams_FTable.c
  ldt/core/LDT_runmode_FTable.c
  ldt/core/LDT_soils_FTable.c
  ldt/core/LDT_statdscale_FTable.c
  ldt/core/LDT_topo_FTable.c
  ldt/lib/xmrg/xmrg_read_data_c.c
  lis/core/LIS_RTM_FTable.c
  lis/core/LIS_alb_FTable.c
  lis/core/LIS_biasestim_FTable.c
  lis/core/LIS_dataassim_FTable.c
  lis/core/LIS_domain_FTable.c
  lis/core/LIS_emiss_FTable.c
  lis/core/LIS_forecastAlg_FTable.c
  lis/core/LIS_gfrac_FTable.c
  lis/core/LIS_glaciermodel_FTable.c
  lis/core/LIS_irrigation_FTable.c
  lis/core/LIS_laisai_FTable.c
  lis/core/LIS_lakemodel_FTable.c
  lis/core/LIS_landslide_FTable.c
  lis/core/LIS_lsm_FTable.c
  lis/core/LIS_metforcing_FTable.c
  lis/core/LIS_openwater_FTable.c
  lis/core/LIS_optUE_FTable.c
  lis/core/LIS_perturb_FTable.c
  lis/core/LIS_roughness_FTable.c
  lis/core/LIS_routing_FTable.c
  lis/core/LIS_runmode_FTable.c
  lis/core/LIS_runoffdata_FTable.c
  lis/core/xmrg_read_data_c.c
  lis/params/gfrac/SPORTDaily/cppfunmodis.h
  lis/params/gfrac/SPORTDaily/read_SPORTgfrac.F90
  lis/params/gfrac/SPORTDaily/read_gvf_binary_modis.cc
  lis/params/gfrac/VIIRSDaily/cppfunviirs.h
  lis/params/gfrac/VIIRSDaily/read_VIIRSgfrac.F90
  lis/params/gfrac/VIIRSDaily/read_gvf_binary_viirs.cc
  lvt/core/LVT_domain_FTable.c
  lvt/core/LVT_obs_FTable.c
  lvt/core/LVT_runmode_FTable.c
  lvt/core/LVT_training_FTable.c
  lvt/utils/gnuplot/timeseries/plotTS.py
Labels: BugFix, HighPriority

#369 Fix ECMWF reanalysis metforcing big_endian data read in LIS
  lis/metforcing/ecmwfreanal/read_ecmwfreanal.F90
Labels: BugFix, LowPriority

#367 Update Dateline Fix LIS Testcase files
  lis/testcases/domains/latlon_idlcross/ldt.config
  lis/testcases/domains/latlon_idlcross/lis.config
Labels: AddToTestSuite

#375 Update LVT Reference ET config documentation
  lvt/configs/lvt.config.adoc
  lvt/configs/lvt.config.master
Labels: Documentation

#376 Fix Metric Output Directory config check in LVT
  lvt/core/LVT_readConfig.F90
Labels: BugFix

#385 Ensure sub-directories are created with WMO convention output style
  lis/core/LIS_fileIOMod.F90
Labels: BugFix, HighPriority

#386 Prevent LIS from writing ASCII statistics data when option is off
  lis/core/LIS_historyMod.F90
Labels: BugFix

#391 Fix read restart
  lis/core/LIS_historyMod.F90
  lis/testcases/surfacemodels/land/noah.3.6_restart/MODEL_OUTPUT_LIST.TBL
  lis/testcases/surfacemodels/land/noah.3.6_restart/README
  lis/testcases/surfacemodels/land/noah.3.6_restart/input.ctl
  lis/testcases/surfacemodels/land/noah.3.6_restart/input.xdf
  lis/testcases/surfacemodels/land/noah.3.6_restart/input_testcase.ctl
  lis/testcases/surfacemodels/land/noah.3.6_restart/ldt.config
  lis/testcases/surfacemodels/land/noah.3.6_restart/lis.config
  lis/testcases/surfacemodels/land/noah.3.6_restart/output.ctl
  lis/testcases/surfacemodels/land/noah.3.6_restart/testcase.ctl
Labels: BugFix, HighPriority
