Repository NASA-LIS/LISF, pull requests merged in 2019-12, with the labels that each got.

#414 CRITICAL BUG FIX: Added "-" units for RelSMC in LVT
  lvt/core/LVT_LISoutputHandlerMod.F90
  lvt/core/LVT_histDataMod.F90
Labels: BugFix, HighPriority

#417 Fix/snowcover for LVT "557 post" runmode
  lvt/utils/afwa/templates/MODEL_OUTPUT_LIST.TBL.lvt_557post.Snowcover_inst.3hr
  lvt/utils/afwa/templates/make_lvt_config_3hr_jules.py
  lvt/utils/afwa/templates/submit_lvt_conrad_3hr_jules.py
  lvt/utils/afwa/templates/submit_lvt_discover_3hr_jules.py
Labels: BugFix, HighPriority

#418 Updated RHMin calculation in NoahMP.4.0.1.
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90
Labels: BugFix, HighPriority

#423 Changed NoahMP soil thickness units to centimeters in history output.
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_lsmMod.F90
Labels: BugFix, HighPriority

#425 Added Greenness_inst for Noah and NoahMP.
  lvt/utils/afwa/run_ncks.py
Labels: BugFix, HighPriority

#415 Bug fixes for LDTSI
  ldt/LDTSI/LDTSI_analysisMod.F90
  ldt/LDTSI/ldt.config.sample
  lvt/configs/lvt.config.ldtsi
Labels: BugFix, HighPriority

#426 Remove string "version 7.2r" from configure and compile messages
  ldt/compile
  ldt/configure
  lis/compile
  lis/configure
  lvt/compile
  lvt/configure
Labels: BugFix, HighPriority

#219 Enables the support for LPRM VOD in LVT
  lvt/configs/lvt.config.master
  lvt/datastreams/LPRMvod/LPRM_vodobsMod.F90
  lvt/datastreams/LPRMvod/readLPRMvodobs.F90
  lvt/make/Filepath
  lvt/plugins/LVT_datastream_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: enhancement

#422 Fix/410 ldtbuffer
  ldt/core/LDT_SurfaceTypeMod.F90
  ldt/core/LDT_domainMod.F90
  ldt/core/LDT_gridmappingMod.F90
  ldt/core/LDT_topoMod.F90
  ldt/domains/latlon/readinput_latlon.F90
  ldt/interp/compute_earth_coord.F90
  ldt/interp/compute_earth_coord_latlon.F90
  ldt/interp/compute_grid_coord.F90
  ldt/interp/compute_grid_coord_latlon.F90
  ldt/interp/get_fieldpos.F90
  ldt/interp/upscaleByAveraging_input.F90
  ldt/interp/upscaleByCnt.F90
  ldt/params/landcover/read_MODISNative_lc.F90
  lis/core/LIS_domainMod.F90
  lis/testcases/domains/lambert_buffer/MODEL_OUTPUT_LIST.TBL
  lis/testcases/domains/lambert_buffer/README
  lis/testcases/domains/lambert_buffer/input.ctl
  lis/testcases/domains/lambert_buffer/input_testcase.ctl
  lis/testcases/domains/lambert_buffer/ldt.config
  lis/testcases/domains/lambert_buffer/lis.config
  lis/testcases/domains/lambert_buffer/output.ctl
  lis/testcases/domains/lambert_buffer/testcase.ctl
  lis/testcases/domains/latlon_idlcross/lis.config
Labels: AddToTestSuite, BugFix

#433 Add GEFS forcing reader
  lis/configs/lis.config.adoc
  lis/make/default.cfg
  lis/metforcing/gefs/0Intro_gefs.txt
  lis/metforcing/gefs/finalize_gefs.F90
  lis/metforcing/gefs/gefs_forcingMod.F90
  lis/metforcing/gefs/get_gefs.F90
  lis/metforcing/gefs/interp_gefs.F90
  lis/metforcing/gefs/read_gefs_reforecast.F90
  lis/metforcing/gefs/readcrd_gefs.F90
  lis/metforcing/gefs/reset_gefs.F90
  lis/metforcing/gefs/timeinterp_gefs.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
  lis/testcases/metforcing/gefs/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/gefs/README
  lis/testcases/metforcing/gefs/input.ctl
  lis/testcases/metforcing/gefs/input_testcase.ctl
  lis/testcases/metforcing/gefs/ldt.config
  lis/testcases/metforcing/gefs/lis.config
  lis/testcases/metforcing/gefs/output.ctl
  lis/testcases/metforcing/gefs/testcase.ctl
Labels: AddToTestSuite, enhancement

#430 Change the 'LDTSI' to 'USAFSI' in LDT configuration
  ldt/LDTSI/LDTSI_binary.F90
  ldt/LDTSI/ldt.config.sample
  ldt/USAFSI/LDT_bratsethMod.F90
  ldt/USAFSI/LDT_usafsiMod.F90
  ldt/USAFSI/USAFSI_analysisMod.F90
  ldt/USAFSI/USAFSI_arraysMod.F90
  ldt/USAFSI/USAFSI_binary.F90
  ldt/USAFSI/USAFSI_blacklist.cfg
  ldt/USAFSI/USAFSI_gofsMod.F90
  ldt/USAFSI/USAFSI_lisMod.F90
  ldt/USAFSI/USAFSI_netcdfMod.F90
  ldt/USAFSI/USAFSI_paramsMod.F90
  ldt/USAFSI/USAFSI_run.F90
  ldt/USAFSI/USAFSI_ssmisMod.F90
  ldt/USAFSI/USAFSI_utilMod.F90
  ldt/USAFSI/ldt.config.sample
  ldt/USAFSI/ztif.c
  ldt/USAFSI/ztif.h
  ldt/USAFSI/ztif_frac.c
  ldt/USAFSI/ztif_frac_slice.c
  ldt/USAFSI/ztif_read.c
  ldt/USAFSI/ztif_write.c
  ldt/configs/ldt.config.adoc
  ldt/configs/ldt.config_master
  ldt/make/Filepath
  ldt/plugins/LDT_pluginIndices.F90
  ldt/plugins/LDT_runmode_pluginMod.F90
  ldt/runmodes/USAFSI/LDT_init_usafsi.F90
  ldt/runmodes/USAFSI/LDT_run_usafsi.F90
Labels: HighPriority, NotReady, enhancement

#431 Rename 'LDTSI' da observation in LIS configuration to 'USAFSI'
  lis/configs/lis.config.adoc
  lis/dataassim/obs/USAFSI/USAFSIobs_Mod.F90
  lis/dataassim/obs/USAFSI/read_USAFSIobs.F90
  lis/dataassim/obs/USAFSI/write_USAFSIobs.F90
  lis/make/default.cfg
  lis/make/plugins.py
  lis/plugins/LIS_DAobs_pluginMod.F90
  lis/plugins/LIS_lsmda_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_descale_usafsi.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_getusafsipred.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_getusafsivars.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_map_usafsi.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_qc_usafsiobs.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_qcusafsi.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_scale_usafsi.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_setusafsivars.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_transform_usafsi.F90
  lis/surfacemodels/land/noah.3.9/da_usafsi/noah39_updateusafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_dausafsi_Mod.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_descale_usafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_getusafsipred.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_getusafsivars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_map_usafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_qc_usafsiobs.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_qcusafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_scale_usafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_setusafsivars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_transform_usafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_updateusafsivars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_usafsi_update.F90
Labels: HighPriority, NotReady, enhancement

#437 Replaces "LDTSI" with "USAFSI" in LVT
  lvt/configs/lvt.config.adoc
  lvt/configs/lvt.config.master
  lvt/configs/lvt.config.usafsi
  lvt/core/LVT_PRIV_rcMod.F90
  lvt/make/Filepath
  lvt/plugins/LVT_pluginIndices.F90
  lvt/plugins/LVT_runmode_pluginMod.F90
  lvt/runmodes/USAFSIpost/LVT_USAFSIpostMod.F90
  lvt/runmodes/USAFSIpost/LVT_gribWrapperMod.F90
  lvt/runmodes/USAFSIpost/LVT_init_USAFSIpost.F90
  lvt/runmodes/USAFSIpost/LVT_run_USAFSIpost.F90
  lvt/runmodes/USAFSIpost/lvt.config.example
Labels: BugFix, HighPriority, NotReady

#439 Added Elevation to exception list for smoothing.
  lvt/core/LVT_DataStreamsMod.F90
Labels: BugFix, HighPriority

#440 Fix for domains crossing PM in LDT
  ldt/core/LDT_fileIOMod.F90
  ldt/interp/compute_earth_coord_latlon.F90
Labels: BugFix, HighPriority
