Repository NASA-LIS/LISF, pull requests merged in 2020-09, with the labels that each got.

#579 Fix LVT SMAP readers
  lvt/datastreams/SMAPTB/readSMAPTBobs.F90
  lvt/datastreams/SMAP_L3TB/readSMAP_L3TB.F90
  lvt/datastreams/SMAPvod/readSMAPvodobs.F90
Labels: BugFix

#580 Add sample CDF and ensemble restart ldt.config files for 557WW
  lis/configs/557WW-7.3-FOC/ldt.config.global.jules50.cdf
  lis/configs/557WW-7.3-FOC/ldt.config.global.jules50.ensemble
  lis/configs/557WW-7.3-FOC/ldt.config.global.noah39.cdf
  lis/configs/557WW-7.3-FOC/ldt.config.global.noah39.ensemble
  lis/configs/557WW-7.3-FOC/ldt.config.global.noahmp401.cdf
  lis/configs/557WW-7.3-FOC/ldt.config.global.noahmp401.ensemble
Labels: enhancement

#585 Fix instructions for compiling w/ user.cfg
  docs/LIS_users_guide/plugins.adoc
Labels: Documentation

#370 Awral
  lis/arch/Config.pl
  lis/configs/MODEL_OUTPUT_LIST.TBL.adoc
  lis/configs/lis.config.adoc
  lis/core/LIS_histDataMod.F90
  lis/make/default.cfg
  lis/metforcing/AWRAL/AWRAL_forcingMod.F90
  lis/metforcing/AWRAL/finalize_AWRAL.F90
  lis/metforcing/AWRAL/get_AWRAL.F90
  lis/metforcing/AWRAL/interp_AWRAL.F90
  lis/metforcing/AWRAL/read_AWRAL.F90
  lis/metforcing/AWRAL/readcrd_AWRAL.F90
  lis/metforcing/AWRAL/reset_AWRAL.F90
  lis/metforcing/AWRAL/timeinterp_AWRAL.F90
  lis/plugins/LIS_lsm_pluginMod.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_coldstart.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_dynsetup.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_f2t.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_finalize.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_lsmMod.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_main.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_module.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_readcrd.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_readrst.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_setup.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_writerst.F90
  lis/surfacemodels/land/awral.6.0.0/physics/awral.c
  lis/surfacemodels/land/awral.6.0.0/physics/awral.h
  lis/surfacemodels/land/awral.6.0.0/physics/build_icc.sh
  lis/testcases/surfacemodels/land/awral.6.0.0/AWRAL600_OUTPUT_LIST.TBL
  lis/testcases/surfacemodels/land/awral.6.0.0/INPUT/forcing_variables.txt
  lis/testcases/surfacemodels/land/awral.6.0.0/INPUT/tile_fractions.dat
  lis/testcases/surfacemodels/land/awral.6.0.0/README
  lis/testcases/surfacemodels/land/awral.6.0.0/lis.config
Labels: AddToTestSuite, LISF7.4, enhancement
