Repository NASA-LIS/LISF, pull requests merged in 2020-07, with the labels that each got.

#542 Updated LVT to have more flexible time lag computations
  lvt/core/LVT_LISoutputHandlerMod.F90
  lvt/core/LVT_LMLCMod.F90
  lvt/core/LVT_PRIV_rcMod.F90
  lvt/core/LVT_coreMod.F90
  lvt/core/LVT_domainMod.F90
  lvt/core/LVT_readConfig.F90
  lvt/core/LVT_soilsMod.F90
  lvt/core/LVT_topoMod.F90
  lvt/metrics/LVT_InformationEntropyMod.F90
  lvt/metrics/LVT_MaxTimeMod.F90
  lvt/metrics/LVT_MinTimeMod.F90
Labels: AddToTestSuite, enhancement

#548 SMAP QC flag was removed
  lis/dataassim/obs/SMAP_NRTsm/SMAPNRTsm_Mod.F90
Labels: BugFix

#552 Remove SMAP(NASA) LIS DA QC check config entry
  lis/configs/lis.config.adoc
  lis/dataassim/obs/NASA_SMAPsm/NASASMAPsm_Mod.F90
  lis/dataassim/obs/NASA_SMAPsm/read_NASASMAPsm.F90
Labels: enhancement

#550 Adds the support for JASMIN soil moisture analysis
  lvt/configs/lvt.config.adoc
  lvt/datastreams/jasmin/JASMINsm_obsMod.F90
  lvt/datastreams/jasmin/readJASMINsmObs.F90
  lvt/make/Filepath
  lvt/plugins/LVT_datastream_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: AddToTestSuite, enhancement
