Repository NASA-LIS/LISF, pull requests merged in 2020-12, with the labels that each got.

#642 Minor tweaks to Noah-MP config entries for LIS Users' Guide
  lis/configs/lis.config.adoc
Labels: Documentation

#646 Adds the support for ERA5 in LVT
  lvt/configs/lvt.config.adoc
  lvt/datastreams/ERA5/ERA5obsMod.F90
  lvt/datastreams/ERA5/readERA5obs.F90
  lvt/make/Filepath
  lvt/plugins/LVT_datastream_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: enhancement

#649 Update build instructions for LIS 7.3
  docs/LIS_users_guide/LIS_usersguide.adoc
  docs/LIS_users_guide/build.adoc
  docs/LIS_users_guide/build_examples.adoc
  docs/LIS_users_guide/plugins.adoc
  docs/LIS_users_guide/user_cfg_table.adoc
Labels: Documentation

#647 Added ability to read WWMCA GRIB1 files instead of binary
  lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.jules50.discover
  lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.noah39.discover
  lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.noahmp401.discover
  lis/configs/557WW-7.3-FOC/lis.config.global.jules50.ops
  lis/configs/557WW-7.3-FOC/lis.config.global.jules50.ops.galwem10
  lis/configs/557WW-7.3-FOC/lis.config.global.jules50.retrospective
  lis/configs/557WW-7.3-FOC/lis.config.global.noah39.ops
  lis/configs/557WW-7.3-FOC/lis.config.global.noah39.ops.galwem10
  lis/configs/557WW-7.3-FOC/lis.config.global.noah39.retrospective
  lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.ops
  lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.ops.galwem10
  lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.retrospective
  lis/configs/lis.config.adoc
  lis/metforcing/usaf/AGRMET_forcingMod.F90
  lis/metforcing/usaf/USAF_WWMCA_grib1Mod.F90
  lis/metforcing/usaf/compute_type_based_clouds.F90
  lis/metforcing/usaf/readcrd_agrmet.F90
Labels: HighPriority, enhancement

#659 Feature/modislaireader
  ldt/DAobs/MCD15A2H_LAI/MCD15A2Hlai_obsMod.F90
  ldt/DAobs/MCD15A2H_LAI/readMCD15A2HlaiObs.F90
  ldt/configs/ldt.config.adoc
  ldt/make/Filepath
  ldt/plugins/LDT_DAobs_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
Labels: enhancement

#661 Fixed type declaration for variable found_inq.
  ldt/USAFSI/USAFSI_galwemMod.F90
Labels: BugFix, HighPriority

#662 Update devonly guards in Users' Guides for LISF 7.3 release
  docs/LIS_users_guide/LIS_usersguide.adoc
  docs/LIS_users_guide/obtain-source.adoc
  ldt/configs/ldt.config.adoc
  lis/configs/lis.config.adoc
Labels: Documentation

#665 Correct broken links in Users' Guides for LISF 7.3 release
  ldt/configs/ldt.config.adoc
  lis/configs/lis.config.adoc
Labels: Documentation

#656 Fix garbage lislog output when writing model output
  lis/core/LIS_RTMMod.F90
  lis/core/LIS_irrigationMod.F90
  lis/core/LIS_surfaceModelMod.F90
  lis/routing/HYMAP2_router/HYMAP2_routing_output.F90
  lis/routing/HYMAP_router/HYMAP_routing_output.F90
  lis/routing/NLDAS_router/NLDAS_routing_output.F90
Labels: BugFix

#667 Clean up LIS Users' Guide for LISF 7.3 release
  docs/LIS_users_guide/intro.adoc
  docs/LIS_users_guide/obtain-source.adoc
  docs/LIS_users_guide/support.adoc
Labels: Documentation

#668 Clean up LVT Users' Guide for LISF 7.3 release
  lvt/configs/lvt.config.adoc
Labels: Documentation

#669 Remove LaTeX files for LISF 7.3 release
  ldt/configs/ldt.config_master
  lvt/configs/METRICS.TBL
  lvt/configs/MODEL_OUTPUT_LIST_LVT.TBL
  lvt/configs/lvt.config.master
Labels: Documentation

#670 Prevent divide-by-zero in Noah-MP with frozen soils
  lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
Labels: BugFix

#678 Update revision history of Users' Guides for LISF 7.3 release
  docs/LDT_users_guide/LDT_usersguide.adoc
  docs/LDT_users_guide/revision_table.adoc
  docs/LIS_users_guide/LIS_usersguide.adoc
  docs/LIS_users_guide/revision_table.adoc
  docs/LVT_users_guide/LVT_usersguide.adoc
  docs/LVT_users_guide/revision_table.adoc
Labels: Documentation

#663 lai_da for noahmp.4.0.1 and MODIS MCD15A2H LAI reader for LIS
  lis/configs/lis.config.adoc
  lis/dataassim/obs/MCD15A2H_LAI/MCD15A2Hlai_Mod.F90
  lis/dataassim/obs/MCD15A2H_LAI/read_MCD15A2Hlai.F90
  lis/dataassim/obs/MCD15A2H_LAI/write_MCD15A2Hlai.F90
  lis/make/default.cfg
  lis/plugins/LIS_DAobs_pluginMod.F90
  lis/plugins/LIS_lsmda_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_daveg_Mod.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_descale_veg.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_getLAIpred.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_getvegvars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_qc_LAIobs.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_qcveg.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_scale_veg.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_setvegvars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_updatevegvars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_write_veg.F90
Labels: enhancement
