Repository NASA-LIS/LISF, pull requests merged in 2020-03, with the labels that each got.

#474 Added entry for GALWEM nominal resolution in kilometers.
  lis/configs/lis.config.adoc
Labels: Documentation, HighPriority

#459 Add residual snow fix option to Noah.3.6
  lis/configs/lis.config.adoc
  lis/surfacemodels/land/noah.3.6/module_sf_noah36lsm.F90
  lis/surfacemodels/land/noah.3.6/noah36_lsmMod.F90
  lis/surfacemodels/land/noah.3.6/noah36_main.F90
  lis/surfacemodels/land/noah.3.6/noah36_readcrd.F90
Labels: NotReady, enhancement

#475 Enable build tools to use either Python2 or Python3
  ldt/make/makedep.py
  lis/make/makedep.py
  lis/make/plugins.py
  lvt/make/makedep.py
Labels: BugFix

#457 Adds a plugin for ALEXI ESI data in LVT
  lvt/core/LVT_LISoutputHandlerMod.F90
  lvt/core/LVT_histDataMod.F90
  lvt/datastreams/ALEXIesi/ALEXIesi_obsMod.F90
  lvt/datastreams/ALEXIesi/readALEXIesiObs.F90
  lvt/make/Filepath
  lvt/plugins/LVT_datastream_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: enhancement

#480 Reformat LISF build tools to conform to PEP8
  ldt/make/makedep.py
  lis/make/makedep.py
  lis/make/plugins.py
  lvt/make/makedep.py
Labels: BugFix, HighPriority

#489 Support for compiling on SLES 12
  docs/creating_a_custom_modulefile/Makefile
  docs/creating_a_custom_modulefile/bashrc
  docs/creating_a_custom_modulefile/creating-a-custom-modulefile.adoc
  docs/creating_a_custom_modulefile/profile
  docs/creating_a_custom_modulefile/sample_intel_18_0_3_222
  env/discover/lisf_7_intel_18_0_3_222
  env/discover/lisf_7_intel_19_1_0_166
  ldt/arch/Config.pl
  lis/arch/Config.pl
  lis/make/Makefile
  lvt/arch/Config.pl
Labels: HighPriority
