Repository NASA-LIS/LISF, pull requests merged in 2020-08, with the labels that each got.

#566 Added Albedo_tavg and SmLiqFrac_inst to merging scripts for JULES.
  lvt/utils/afwa/cat_lvt_grib2.py
  lvt/utils/afwa/run_ncks.py
Labels: BugFix, HighPriority

#568 Fix/jules 1snow
  lis/configs/557WW-7.3-FOC/JULES/README
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/Loobos_1997.dat
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/ancillaries.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/crop_params.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/drive.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/fire.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/gen_time.py
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/imogen.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/initial_conditions.dat
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/initial_conditions.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_hydrology.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_radiation.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_rivers.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_snow.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_soil.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_soil_biogeochem.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_soil_ecosse.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_surface.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_surface_types.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/jules_vegetation.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/model_grid.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/nveg_params.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/output.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/pft_params.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/prescribed_data.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/tile_fractions.dat
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/timesteps.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/triffid_params.nml
  lis/configs/557WW-7.3-FOC/JULES/single_snow_layer/urban.nml
Labels: HighPriority

#577 Fix HYMAP2 routing write ensemble restart routine to compile serial
  lis/routing/HYMAP2_router/HYMAP2_routing_writerst.F90
Labels: bug
