Repository NASA-LIS/LISF, pull requests merged in 2020-06, with the labels that each got.

#531 Add 1 km MERIT DEM (upscaled) for topography parameters
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_topoMod.F90
  ldt/params/topo/read_MERIT1K_aspect.F90
  ldt/params/topo/read_MERIT1K_elev.F90
  ldt/params/topo/read_MERIT1K_slope.F90
  ldt/params/topo/setTopoParmsFullnames.F90
  ldt/plugins/LDT_param_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
Labels: AddToTestSuite

#532 LDT: HyMAP2, Support flexible grid setting (dx~=dy)
  ldt/params/HYMAP/HYMAP_parmsMod.F90
  ldt/params/HYMAP/read_HYMAP_basin.F90
  ldt/params/HYMAP/read_HYMAP_basin_mask.F90
  ldt/params/HYMAP/read_HYMAP_fld_height.F90
  ldt/params/HYMAP/read_HYMAP_flow_dir_x.F90
  ldt/params/HYMAP/read_HYMAP_flow_dir_y.F90
  ldt/params/HYMAP/read_HYMAP_grid_elev.F90
Labels: AddToTestSuite

#535 Fix LIS soil moisture DA QC checks for Noah-MP-4.0.1 LSM
  lis/surfacemodels/land/noahmp.4.0.1/da_soilm/noahmp401_qc_soilmobs.F90
Labels: HighPriority, bug

#537 Implements the relative entropy metric in LVT
  lvt/configs/METRICS.TBL
  lvt/configs/METRICS.TBL.adoc
  lvt/core/LVT_readMetricsAttributes.F90
  lvt/core/LVT_statsDataMod.F90
  lvt/core/LVT_statsMod.F90
  lvt/metrics/LVT_RelativeEntropy.F90
  lvt/plugins/LVT_metric_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: AddToTestSuite, enhancement

#485 Feature/era5forc
  ldt/configs/ldt.config.adoc
  ldt/make/Filepath
  ldt/metforcing/era5/era5_forcingMod.F90
  ldt/metforcing/era5/finalize_era5.F90
  ldt/metforcing/era5/get_era5.F90
  ldt/metforcing/era5/read_era5.F90
  ldt/metforcing/era5/read_era5_elev.F90
  ldt/metforcing/era5/readcrd_era5.F90
  ldt/metforcing/era5/reset_era5.F90
  ldt/metforcing/era5/timeinterp_era5.F90
  ldt/plugins/LDT_metforcing_pluginMod.F90
  ldt/plugins/LDT_param_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
  lis/configs/lis.config.adoc
  lis/make/default.cfg
  lis/metforcing/era5/era5_forcingMod.F90
  lis/metforcing/era5/finalize_era5.F90
  lis/metforcing/era5/get_era5.F90
  lis/metforcing/era5/read_era5.F90
  lis/metforcing/era5/read_era5_elev.F90
  lis/metforcing/era5/readcrd_era5.F90
  lis/metforcing/era5/reset_era5.F90
  lis/metforcing/era5/timeinterp_era5.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
Labels: AddToTestSuite

#539 Fix/noahmp401 soilmda
  lis/surfacemodels/land/noahmp.4.0.1/da_soilm/noahmp401_qc_soilmobs.F90
Labels: BugFix
