Repository NASA-LIS/LISF, pull requests merged in 2020-01, with the labels that each got.

#441 557 post mode now uses Welford algorithm for standard deviation.
  lvt/core/LVT_DataStreamsMod.F90
Labels: BugFix, HighPriority

#450 Revise list of LIS variables to smooth
  lvt/utils/afwa/run_ncks.py
  lvt/utils/afwa/templates/make_lvt_config_24hr_jules.py
  lvt/utils/afwa/templates/make_lvt_config_24hr_noah.py
  lvt/utils/afwa/templates/make_lvt_config_24hr_noahmp.py
  lvt/utils/afwa/templates/make_lvt_config_3hr_jules.py
  lvt/utils/afwa/templates/make_lvt_config_3hr_noah.py
  lvt/utils/afwa/templates/make_lvt_config_3hr_noahmp.py
Labels: BugFix, HighPriority

#451 Feature/noahmp401 snow da
  lis/surfacemodels/land/noahmp.4.0.1/da_snodep/noahmp401_getsnodepvars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_snodep/noahmp401_qcsnodep.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_snodep/noahmp401_setsnodepvars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_snodep/noahmp401_updatesnodepvars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_getusafsivars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_map_usafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_qcusafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_setusafsivars.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_transform_usafsi.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_usafsi/noahmp401_updateusafsivars.F90
Labels: HighPriority

#447 Fix update for domain-added buffer in LDT
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_PRIV_rcMod.F90
  ldt/core/LDT_gridmappingMod.F90
  ldt/core/LDT_readConfig.F90
  ldt/domains/latlon/readinput_latlon.F90
  ldt/params/HYMAP/HYMAP_parmsMod.F90
  ldt/params/HYMAP/read_HYMAP_baseflow_delay.F90
  ldt/params/HYMAP/read_HYMAP_baseflow_dwi_ratio.F90
  ldt/params/HYMAP/read_HYMAP_basin.F90
  ldt/params/HYMAP/read_HYMAP_basin_mask.F90
  ldt/params/HYMAP/read_HYMAP_drain_area.F90
  ldt/params/HYMAP/read_HYMAP_fld_height.F90
  ldt/params/HYMAP/read_HYMAP_fld_z.F90
  ldt/params/HYMAP/read_HYMAP_flow_dir_x.F90
  ldt/params/HYMAP/read_HYMAP_flow_dir_y.F90
  ldt/params/HYMAP/read_HYMAP_flow_type.F90
  ldt/params/HYMAP/read_HYMAP_grid_area.F90
  ldt/params/HYMAP/read_HYMAP_grid_dist.F90
  ldt/params/HYMAP/read_HYMAP_grid_elev.F90
  ldt/params/HYMAP/read_HYMAP_refq.F90
  ldt/params/HYMAP/read_HYMAP_river_height.F90
  ldt/params/HYMAP/read_HYMAP_river_length.F90
  ldt/params/HYMAP/read_HYMAP_river_width.F90
  ldt/params/HYMAP/read_HYMAP_river_z.F90
  ldt/params/HYMAP/read_HYMAP_runoff_delay.F90
  ldt/params/HYMAP/read_HYMAP_runoff_delaym.F90
  ldt/params/HYMAP/read_HYMAP_runoff_dwi_ratio.F90
Labels: BugFix, NotReady
