Repository NASA-LIS/LISF, pull requests merged in 2020-10, with the labels that each got.

#601 Feature/rst transform
  ldt/USAFSI/USAFSI_run.F90
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_ANNMod.F90
  ldt/core/LDT_DAmetricsMod.F90
  ldt/core/LDT_DAobsDataMod.F90
  ldt/core/LDT_PRIV_rcMod.F90
  ldt/core/LDT_climoRstProcMod.F90
  ldt/core/LDT_coreMod.F90
  ldt/core/LDT_domainMod.F90
  ldt/core/LDT_domain_FTable.c
  ldt/core/LDT_ensRstMod.F90
  ldt/core/LDT_fileIOMod.F90
  ldt/core/LDT_gridmappingMod.F90
  ldt/core/LDT_historyMod.F90
  ldt/core/LDT_metforcingMod.F90
  ldt/core/LDT_paramOptCheckMod.F90
  ldt/core/LDT_paramProcMod.F90
  ldt/core/LDT_readConfig.F90
  ldt/core/LDT_rstTransformProcMod.F90
  ldt/domains/UTM/readinput_UTM.F90
  ldt/domains/easev2/readinput_easev2.F90
  ldt/domains/gaussian/readinput_gaussian.F90
  ldt/domains/hrap/readinput_hrap.F90
  ldt/domains/lambert/readinput_lambert.F90
  ldt/domains/latlon/readinput_latlon.F90
  ldt/domains/merc/readinput_merc.F90
  ldt/domains/polar/readinput_polar.F90
  ldt/make/Filepath
  ldt/metforcing/nldas1/read_nldas1_elev.F90
  ldt/metforcing/nldas2/read_nldas2_elev.F90
  ldt/params/crop_parms/Monfredaetal08_crops_module.F90
  ldt/params/crop_parms/read_UMDCROPMAP_croptype.F90
  ldt/params/landcover/read_AVHRR_GFS_lc.F90
  ldt/params/landcover/read_AVHRR_lc.F90
  ldt/params/landcover/read_ISA_lc.F90
  ldt/params/landcover/read_MODISNative_lc.F90
  ldt/params/landcover/read_MODIS_lc.F90
  ldt/params/landcover/read_USGSNative_lc.F90
  ldt/params/landcover/read_USGS_lc.F90
  ldt/params/landcover/read_VIC411_lc.F90
  ldt/params/landcover/read_VIC412_lc.F90
  ldt/params/mask/read_maskfile.F90
  ldt/params/topo/read_GTOPO30Native_elev.F90
  ldt/params/topo/read_MERIT1K_aspect.F90
  ldt/params/topo/read_MERIT1K_elev.F90
  ldt/params/topo/read_MERIT1K_slope.F90
  ldt/params/topo/read_SRTM_Native_aspect.F90
  ldt/params/topo/read_SRTM_Native_elev.F90
  ldt/params/topo/read_SRTM_Native_slope.F90
  ldt/plugins/LDT_pluginIndices.F90
  ldt/plugins/LDT_runmode_pluginMod.F90
  ldt/runmodes/climoRstproc/LDT_init_climoRstproc.F90
  ldt/runmodes/climoRstproc/LDT_run_climoRstproc.F90
  ldt/runmodes/rstTransformProc/LDT_init_rstTransformProc.F90
  ldt/runmodes/rstTransformProc/LDT_run_rstTransformProc.F90
  ldt/statDscale/Climo/forcingClimoMod.F90
Labels: enhancement

#609 Fix AWRAL compile and run errors w/ GNU4 compiler
  lis/metforcing/AWRAL/read_AWRAL.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_finalize.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_lsmMod.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_module.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_readrst.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_setup.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_writerst.F90
Labels: BugFix

#612 Add details to how met forcing overlays work to User Guides
  ldt/configs/ldt.config.adoc
  lis/configs/lis.config.adoc
Labels: Documentation

#604 Add check for routing model selection in DA subroutines. [FIX]
  lis/core/LIS_dataAssimMod.F90
  lis/core/LIS_routingMod.F90
Labels: BugFix
