Repository NASA-LIS/LISF, pull requests merged in 2021-04, with the labels that each got.

#756 Added the support for THySM soil moisture
  ldt/DAobs/THySM/THySM_obsMod.F90
  ldt/DAobs/THySM/readTHySMobs.F90
  ldt/core/LDT_DAmetricsMod.F90
  ldt/make/Filepath
  ldt/plugins/LDT_DAobs_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
  lis/dataassim/obs/THySM/THySM_Mod.F90
  lis/dataassim/obs/THySM/read_THySM.F90
  lis/dataassim/obs/THySM/write_THySM.F90
  lis/make/default.cfg
  lis/plugins/LIS_DAobs_pluginMod.F90
  lis/plugins/LIS_lsmda_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
  lvt/datastreams/THySM/THySM_obsMod.F90
  lvt/datastreams/THySM/readTHySMobs.F90
  lvt/datastreams/UASMAP/UASMAP_obsMod.F90
  lvt/datastreams/UASMAP/readUASMAPobs.F90
  lvt/make/Filepath
  lvt/plugins/LVT_datastream_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: enhancement

#759 Add AMSR2 snow depth DA to NoahMP.4.0.1
  lis/dataassim/obs/GCOMW_AMSR2L3SND/GCOMW_AMSR2L3SND_Mod.F90
  lis/dataassim/obs/GCOMW_AMSR2L3SND/read_GCOMW_AMSR2L3SND.F90
  lis/plugins/LIS_lsmda_pluginMod.F90
Labels: enhancement

#762 Feature/swchanges
  lis/core/LIS_coreMod.F90
  lis/core/LIS_dataAssimMod.F90
  lis/core/LIS_histDataMod.F90
  lis/dataassim/obs/hydrowebWL/hydrowebWLobs_module.F90
  lis/dataassim/obs/hydrowebWL/read_hydrowebWLobs.F90
  lis/dataassim/obs/hydrowebWL/write_hydrowebWLobs.F90
  lis/make/default.cfg
  lis/plugins/LIS_DAobs_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
  lis/plugins/LIS_routingda_pluginMod.F90
  lis/routing/HYMAP2_router/HYMAP2_initMod.F90
  lis/routing/HYMAP2_router/HYMAP2_model.F90
  lis/routing/HYMAP2_router/HYMAP2_modelMod.F90
  lis/routing/HYMAP2_router/HYMAP2_model_core.F90
  lis/routing/HYMAP2_router/HYMAP2_resopMod.F90
  lis/routing/HYMAP2_router/HYMAP2_routingMod.F90
  lis/routing/HYMAP2_router/HYMAP2_routing_readrst.F90
  lis/routing/HYMAP2_router/HYMAP2_routing_reset.F90
  lis/routing/HYMAP2_router/HYMAP2_routing_run.F90
  lis/routing/HYMAP2_router/HYMAP2_routing_writerst.F90
  lis/routing/HYMAP2_router/HYMAP2_urbanMod.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_daWL_Mod.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_descale_WL.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_getStateSpaceSize.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_getWL.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_getWLpred.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_qcWL.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_qc_WLobs.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_scale_WL.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_setPertStates.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_setWL.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_updateWL.F90
  lis/routing/HYMAP2_router/da_WL/HYMAP2_write_WL.F90
  lis/surfacemodels/land/clsm.f2.5/clsmf25_lsmMod.F90
  lis/surfacemodels/land/clsm.f2.5/clsmf25_main.F90
  lis/surfacemodels/land/clsm.f2.5/clsmf25_model.F90
  lis/surfacemodels/land/clsm.f2.5/clsmf25_types.F90
  lis/surfacemodels/land/clsm.f2.5/routing/clsmf25_getsws_hymap2.F90
  lis/surfacemodels/land/noah.3.6/module_sf_noah36lsm.F90
  lis/surfacemodels/land/noah.3.6/noah36_lsmMod.F90
  lis/surfacemodels/land/noah.3.6/noah36_main.F90
  lis/surfacemodels/land/noah.3.6/noah36_module.F90
  lis/surfacemodels/land/noah.3.6/routing/noah36_getsws_hymap2.F90
  lis/surfacemodels/land/noahmp.3.6/NoahMP36_coldstart.F90
  lis/surfacemodels/land/noahmp.3.6/NoahMP36_lsmMod.F90
  lis/surfacemodels/land/noahmp.3.6/module_sf_noahmplsm_36.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_lsmMod.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_module.F90
  lis/surfacemodels/land/noahmp.4.0.1/noahmp_driver_401.F90
  lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90
  lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
  lis/surfacemodels/land/noahmp.4.0.1/routing/noahmp401_getsws_hymap2.F90
Labels: HighPriority, enhancement

#757 Add documentation for THySM config options
  ldt/configs/ldt.config.adoc
  lis/configs/lis.config.adoc
  lvt/configs/lvt.config.adoc
Labels: Documentation

#765 Fix/557ww 7.4 configs
  lis/configs/557WW-7.4-FOC/attribs/jules_sm_pertattribs.txt
  lis/configs/557WW-7.4-FOC/attribs/noah_sm_pertattribs.txt
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.jules50.cdf
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.noah39.cdf
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.noahmp401.cdf
  lis/configs/557WW-7.4-FOC/for_discover/lis.config.global.jules50.discover
  lis/configs/557WW-7.4-FOC/for_discover/lis.config.global.noah39.discover
  lis/configs/557WW-7.4-FOC/for_discover/lis.config.global.noahmp401.discover
  lis/configs/557WW-7.4-FOC/lis.config.global.jules50.ops
  lis/configs/557WW-7.4-FOC/lis.config.global.jules50.ops.galwem10
  lis/configs/557WW-7.4-FOC/lis.config.global.noah39.ops
  lis/configs/557WW-7.4-FOC/lis.config.global.noah39.ops.galwem10
  lis/configs/557WW-7.4-FOC/lis.config.global.noahmp401.ops
  lis/configs/557WW-7.4-FOC/lis.config.global.noahmp401.ops.galwem10
Labels: LISF7.4

#766 Added additional documentation to config ALEXI in LVT
  lvt/configs/lvt.config.adoc
Labels: Documentation

#764 Add support for SNODAS DA in NoahMP4.0.1
  lis/dataassim/obs/SNODAS/SNODAS_Mod.F90
  lis/dataassim/obs/SNODAS/read_SNODAS.F90
  lis/dataassim/obs/SNODAS/write_SNODAS.F90
  lis/make/default.cfg
  lis/plugins/LIS_DAobs_pluginMod.F90
  lis/plugins/LIS_lsmda_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
Labels: eis-freshwater, enhancement

#767 Add registration call for AMSR2 snow depth DA
  lis/plugins/LIS_lsmda_pluginMod.F90
Labels: BugFix, eis-freshwater

#770 Move #endif to enclose NoahMP401 snow DA plugins
  lis/plugins/LIS_lsmda_pluginMod.F90
Labels: BugFix, eis-freshwater

#773 Eis freshwater MCD15A2H LAI Reader for LVT
  lvt/configs/lvt.config.adoc
  lvt/datastreams/MCD15A2H/MCD15A2H_obsMod.F90
  lvt/datastreams/MCD15A2H/readMCD15A2Hobs.F90
  lvt/make/Filepath
  lvt/plugins/LVT_datastream_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: eis-freshwater, enhancement
