Repository NASA-LIS/LISF, pull requests merged in 2021-01, with the labels that each got.

#681 Document missing GRACE config options.
  ldt/configs/ldt.config.adoc
Labels: Documentation

#682 Fix formatting of MODIS LAI options.
  lis/configs/lis.config.adoc
Labels: Documentation

#684 Create OBA output directories (for Air Force LISF 7.4)
  lis/metforcing/usaf/AGRMET_sfcalc.F90
  lis/metforcing/usaf/readagrmetpcpforcing.F90
Labels: LISF7.4, enhancement

#683 Added autotuning software for Air Force Bratseth scheme (for LISF 7.4)
  lis/compile
  lis/utils/afwa/retune_bratseth/README
  lis/utils/afwa/retune_bratseth/cfgs/autotune.cfg
  lis/utils/afwa/retune_bratseth/cfgs/blacklist_gage.cfg
  lis/utils/afwa/retune_bratseth/cfgs/blacklist_rh2m.cfg
  lis/utils/afwa/retune_bratseth/cfgs/blacklist_spd10m.cfg
  lis/utils/afwa/retune_bratseth/cfgs/blacklist_t2m.cfg
  lis/utils/afwa/retune_bratseth/cfgs/gage_cmorph.cfg
  lis/utils/afwa/retune_bratseth/cfgs/gage_geoprecip.cfg
  lis/utils/afwa/retune_bratseth/cfgs/gage_imerg.cfg
  lis/utils/afwa/retune_bratseth/cfgs/gage_nwp.cfg
  lis/utils/afwa/retune_bratseth/cfgs/gage_ssmi.cfg
  lis/utils/afwa/retune_bratseth/cfgs/procOBA_NWP.gage.config
  lis/utils/afwa/retune_bratseth/cfgs/procOBA_NWP.rh2m.config
  lis/utils/afwa/retune_bratseth/cfgs/procOBA_NWP.spd10m.config
  lis/utils/afwa/retune_bratseth/cfgs/procOBA_NWP.t2m.config
  lis/utils/afwa/retune_bratseth/cfgs/procOBA_Sat.cmorph.config
  lis/utils/afwa/retune_bratseth/cfgs/procOBA_Sat.geoprecip.config
  lis/utils/afwa/retune_bratseth/cfgs/procOBA_Sat.imerg.config
  lis/utils/afwa/retune_bratseth/cfgs/procOBA_Sat.ssmi.config
  lis/utils/afwa/retune_bratseth/cfgs/rh2m.cfg
  lis/utils/afwa/retune_bratseth/cfgs/spd10m.cfg
  lis/utils/afwa/retune_bratseth/cfgs/t2m.cfg
  lis/utils/afwa/retune_bratseth/scripts/autotune.py
  lis/utils/afwa/retune_bratseth/scripts/create_blacklist.py
  lis/utils/afwa/retune_bratseth/scripts/customize_lis_config.py
  lis/utils/afwa/retune_bratseth/scripts/customize_procoba_nwp.py
  lis/utils/afwa/retune_bratseth/scripts/customize_procoba_sat.py
  lis/utils/afwa/retune_bratseth/scripts/fit_semivariogram.py
  lis/utils/afwa/retune_bratseth/scripts/plot_semivariogram.py
  lis/utils/afwa/retune_bratseth/scripts/rescale_sat_sigma2.py
  lis/utils/afwa/retune_bratseth/scripts/run_autotune_discover.sh
  lis/utils/afwa/retune_bratseth/scripts/semivar.py
  lis/utils/afwa/retune_bratseth/src/Makefile
  lis/utils/afwa/retune_bratseth/src/USAF_GridHashMod.F90
  lis/utils/afwa/retune_bratseth/src/USAF_ReportsMod.F90
  lis/utils/afwa/retune_bratseth/src/USAF_StationsMod.F90
  lis/utils/afwa/retune_bratseth/src/USAF_sharedMod.F90
  lis/utils/afwa/retune_bratseth/src/future/README
  lis/utils/afwa/retune_bratseth/src/future/USAF_StnOBDictMod.F90
  lis/utils/afwa/retune_bratseth/src/future/USAF_readFilesMod.F90
  lis/utils/afwa/retune_bratseth/src/procOBA_NWP.F90
  lis/utils/afwa/retune_bratseth/src/procOBA_Sat.F90
Labels: LISF7.4, enhancement

#632 Fix HYMAP2 2-way coupling in parallel mode
  lis/configs/lis.config.adoc
  lis/plugins/LIS_lsmrouting_pluginMod.F90
  lis/surfacemodels/land/clsm.f2.5/routing/clsmf25_getsws_hymap2.F90
  lis/surfacemodels/land/noah.3.6/routing/noah36_getrunoffs_hymap2.F90
  lis/surfacemodels/land/noah.3.6/routing/noah36_getsws_hymap2.F90
  lis/surfacemodels/land/noahmp.4.0.1/routing/noahmp401_getsws_hymap2.F90
Labels: enhancement

#687 Fix allocation in LIS_DAobservationsMod
  lis/core/LIS_DAobservationsMod.F90
Labels: BugFix

#686 Update 557WW-7.3-FOC lis.config examples to current settings
  lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.jules50.discover
  lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.noah39.discover
  lis/configs/557WW-7.3-FOC/for_discover/lis.config.global.noahmp401.discover
  lis/configs/557WW-7.3-FOC/lis.config.global.jules50.ops
  lis/configs/557WW-7.3-FOC/lis.config.global.jules50.ops.galwem10
  lis/configs/557WW-7.3-FOC/lis.config.global.jules50.retrospective
  lis/configs/557WW-7.3-FOC/lis.config.global.noah39.ops
  lis/configs/557WW-7.3-FOC/lis.config.global.noah39.ops.galwem10
  lis/configs/557WW-7.3-FOC/lis.config.global.noah39.retrospective
  lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.ops
  lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.ops.galwem10
  lis/configs/557WW-7.3-FOC/lis.config.global.noahmp401.retrospective
Labels: HighPriority

#158 Feature/GLASSalbedo_reader
  lvt/configs/lvt.config.adoc
  lvt/datastreams/GLASSalbedo/readGLASSalbedoObs.F90
Labels: AddToTestSuite, NotReady, enhancement

#685 Change JULES-5.0 snow DA state variable quality control
  lis/surfacemodels/land/jules.5.0/da_snodep/jules50_qcsnodep.F90
  lis/surfacemodels/land/jules.5.0/da_usafsi/jules50_qcusafsi.F90
Labels: HighPriority

#693 Correct typo of HYMAP2 option in lis.config.adoc
  lis/configs/lis.config.adoc
Labels: Documentation

#689 Correct SAC SWE units
  lvt/datastreams/NLDAS2/readNLDAS2data.F90
Labels: BugFix

#692 Fixed grid encoding in Fields file.
  lvt/utils/afwa/convert_nc2surf.py
Labels: BugFix, HighPriority

#696 [LDT] Add revised 10-km snow climatology for USAF-SI analysis
  ldt/USAFSI/LDT_usafsiMod.F90
  ldt/USAFSI/USAFSI_analysisMod.F90
  ldt/USAFSI/USAFSI_run.F90
  ldt/USAFSI/ldt.config.sample
  ldt/configs/ldt.config.adoc
Labels: enhancement

#694 Feature/crocus ldt glacier fraction
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_glacierFractionMod.F90
  ldt/core/LDT_glacier_FTable.c
  ldt/core/LDT_paramProcMod.F90
  ldt/make/Filepath
  ldt/params/Crocus/Crocus_parmsMod.F90
  ldt/params/Crocus/read_CONSTANT_slopetype_cro.F90
  ldt/params/Crocus/read_CONSTANT_tbot_cro.F90
  ldt/params/Crocus/read_ISLSCP1_cro_tbot.F90
  ldt/params/Crocus/read_NCEP_GFS_cro_tbot.F90
  ldt/params/Crocus/read_NCEP_cro_tbot.F90
  ldt/params/glacier/read_GLIMS_glacierfraction.F90
  ldt/params/glacier/setGlacierFracParmsFullnames.F90
  ldt/params/glacier/set_glacierfraction_attribs.F90
  ldt/plugins/LDT_param_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
Labels: enhancement
