Repository NASA-LIS/LISF, pull requests merged in 2021-12, with the labels that each got.

#950 Update modulefile filename in Discover quick start guide
  docs/discover_quick_start/discover_quick_start.adoc
Labels: Documentation

#943 Feature/plumber2
  lis/configs/lis.config.adoc
  lis/make/default.cfg
  lis/metforcing/plumber2/finalize_plumber2.F90
  lis/metforcing/plumber2/get_plumber2.F90
  lis/metforcing/plumber2/plumber2_forcingMod.F90
  lis/metforcing/plumber2/read_plumber2.F90
  lis/metforcing/plumber2/readcrd_plumber2.F90
  lis/metforcing/plumber2/reset_plumber2.F90
  lis/metforcing/plumber2/timeinterp_plumber2.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
  lis/testcases/metforcing/plumber2/NOAHMP401_OUTPUT_PLUMBER2LIST.TBL
  lis/testcases/metforcing/plumber2/input.ctl
  lis/testcases/metforcing/plumber2/lis.config
  lis/testcases/metforcing/plumber2/output.ctl
  lis/testcases/metforcing/plumber2/testcase.ctl
Labels: enhancement, AddToTestSuite, metforcing

#956 This bug fix deallocates variables within the NoahMP401_coldstart
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_coldstart.F90
Labels: BugFix

#957 Deallocate Noah-MP-4.0.1 variables in coldstart for multiple nests
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_coldstart.F90
Labels: BugFix

#958 Fix/retune bratseth
  lis/compile
  lis/utils/usaf/retune_bratseth/cfgs/autotune.cfg
  lis/utils/usaf/retune_bratseth/cfgs/blacklist_spd10m.cfg
  lis/utils/usaf/retune_bratseth/cfgs/blacklist_t2m.cfg
  lis/utils/usaf/retune_bratseth/scripts/autotune.py
  lis/utils/usaf/retune_bratseth/scripts/fit_semivariogram.py
  lis/utils/usaf/retune_bratseth/scripts/run_autotune_discover.sh
Labels: BugFix, HighPriority, LISF7.4
