Repository NASA-LIS/LISF, pull requests merged in 2021-08, with the labels that each got.

#826 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Documentation

#870 Updated Working With GitHub Document to replace URL syntax
  docs/working_with_github/working_with_github.adoc
Labels: Documentation

#873 Updated LISF development workflow diagram
  docs/working_with_github/LISFLOW.drawio
  docs/working_with_github/LISFLOW.png
  docs/working_with_github/working_with_github.adoc
Labels: Cleanup :broom:, Documentation

#867 Feature/obs sim ldt
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_NatRunData_FTable.c
  ldt/core/LDT_OSSEmaskData_FTable.c
  ldt/core/LDT_numericalMethodsMod.F90
  ldt/core/LDT_obsSimMod.F90
  ldt/make/Filepath
  ldt/obsSim/NatureRun/LISout/LISoutNatureRun_Mod.F90
  ldt/obsSim/NatureRun/LISout/readLISoutNatureRun.F90
  ldt/obsSim/OSSEmask/AMSR2/AMSR2OSSEmask_Mod.F90
  ldt/obsSim/OSSEmask/AMSR2/readAMSR2OSSEmask.F90
  ldt/obsSim/OSSEmask/LISout/LISoutOSSEmask_Mod.F90
  ldt/obsSim/OSSEmask/LISout/readLISoutOSSEmask.F90
  ldt/obsSim/OSSEmask/MODIS/MODISOSSEmask_Mod.F90
  ldt/obsSim/OSSEmask/MODIS/readMODISOSSEmask.F90
  ldt/obsSim/OSSEmask/Sentinel1A/Sentinel1AOSSEmask_Mod.F90
  ldt/obsSim/OSSEmask/Sentinel1A/readSentinel1AOSSEmask.F90
  ldt/obsSim/OSSEmask/TSMM/TSMMOSSEmask_Mod.F90
  ldt/obsSim/OSSEmask/TSMM/readTSMMOSSEmask.F90
  ldt/plugins/LDT_NatureRunData_pluginMod.F90
  ldt/plugins/LDT_OSSEmaskData_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
  ldt/plugins/LDT_runmode_pluginMod.F90
  ldt/runmodes/obsSim/LDT_init_obsSim.F90
  ldt/runmodes/obsSim/LDT_run_obsSim.F90
Labels: enhancement

#875 Fix OSSE mask resolution examples
  ldt/configs/ldt.config.adoc
Labels: Documentation

#882 Add snow data assimilation quality control flags to NoahMP401
  lis/surfacemodels/land/noahmp.4.0.1/da_snow/noahmp401_qc_snowobs.F90
Labels: enhancement, eis-freshwater
