Repository NASA-LIS/LISF, pull requests merged in 2021-05, with the labels that each got.

#777 Feature/irrigation-jointDA
  ldt/core/LDT_irrig_Ftable.c
  ldt/core/LDT_irrigationMod.F90
  ldt/params/irrigation/read_USGSNative_irriggwratio.F90
  ldt/params/irrigation/setIrrigParmsFullnames.F90
  ldt/params/irrigation/set_irriggwratio_attribs.F90
  ldt/plugins/LDT_param_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
  lis/configs/lis.config.adoc
  lis/core/LIS_PRIV_rcMod.F90
  lis/core/LIS_irrigationMod.F90
  lis/irrigation/sprinkler/sprinkler_irrigationMod.F90
  lis/plugins/LIS_lsmda_pluginMod.F90
  lis/runmodes/smootherDA/smootherDA_runMod.F90
  lis/surfacemodels/land/noahmp.4.0.1/da_LAI/noahmp401_veg_DAlog.F90
  lis/surfacemodels/land/noahmp.4.0.1/irrigation/noahmp401_getirrigationstates.F90
Labels: eis-freshwater, enhancement

#781 Feature/ansa.da
  lis/dataassim/obs/ANSA_SNWD/read_ANSASNWDsnow.F90
  lis/plugins/LIS_lsmda_pluginMod.F90
Labels: eis-freshwater, enhancement

#788 Feature/relax wb
  lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
Labels: eis-freshwater

#794 add fix to the MCD15A2H and GLASS LAI-DA readers
  lis/dataassim/obs/GLASS_LAI/read_GLASSlai.F90
  lis/dataassim/obs/MCD15A2H_LAI/read_MCD15A2Hlai.F90
Labels: BugFix, eis-freshwater

#779 Adds Noah-MP precipitation timestep fix
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90
Labels: BugFix

#748 Fix GRACE DA for NoahMP.3.6 (LIS) and 0.25 deg GRACE reader (LDT)
  ldt/DAobs/GRACE_tws/GRACEtws_obsMod.F90
  ldt/DAobs/GRACE_tws/readGRACEtwsObs.F90
  lis/dataassim/obs/GRACE/read_GRACEobs.F90
  lis/surfacemodels/land/noahmp.3.6/NoahMP36_readrst.F90
  lis/surfacemodels/land/noahmp.3.6/da_tws/noahmp36_descale_tws.F90
  lis/surfacemodels/land/noahmp.3.6/da_tws/noahmp36_gettws.F90
  lis/surfacemodels/land/noahmp.3.6/da_tws/noahmp36_scale_tws.F90
  lis/surfacemodels/land/noahmp.3.6/da_tws/noahmp36_settws.F90
Labels: BugFix

#801 Add GitHub SSH key setup section
  docs/working_with_github/github-new-ssh-key-button.png
  docs/working_with_github/github-new-ssh-key.png
  docs/working_with_github/github-settings-menu.png
  docs/working_with_github/github-ssh-key-list.png
  docs/working_with_github/github-ssh-menu-item.png
  docs/working_with_github/working_with_github.adoc
Labels: Documentation
