Repository NASA-LIS/LISF, pull requests merged in 2021-07, with the labels that each got.

#821 Update ESA-CCI readers (LDT & LIS) to read combined product versions >2.2
  ldt/DAobs/ESACCI_sm/readESACCIsmObs.F90
  lis/dataassim/obs/ESACCI_sm/read_ESACCIsm.F90
Labels: enhancement

#822 Fix/lvt climo
  lvt/core/LVT_historyMod.F90
  lvt/core/LVT_statsDataMod.F90
  lvt/core/LVT_statsMod.F90
  lvt/metrics/LVT_AnomalyMod.F90
  lvt/utils/afwa/README.soilmoist_anomaly
  lvt/utils/afwa/make_sm_geotiff.py
  lvt/utils/afwa/templates/lvt.config.template_sm_anomaly_jules50
  lvt/utils/afwa/templates/lvt.config.template_sm_anomaly_noah39
  lvt/utils/afwa/templates/lvt.config.template_sm_anomaly_noahmp401
  lvt/utils/afwa/templates/make_lvt_config_sm_anomaly_00z.py
  lvt/utils/afwa/templates/run_lvt.sm_anomaly.discover.sh
Labels: HighPriority, LISF7.4, enhancement

#818 Add new WRF forcing reader in LIS and elev in LDT
  ldt/configs/ldt.config.adoc
  ldt/make/Filepath
  ldt/metforcing/WRFoutv2/WRFoutv2_forcingMod.F90
  ldt/metforcing/WRFoutv2/read_WRFoutv2_elev.F90
  ldt/metforcing/WRFoutv2/readconfig_WRFoutv2.F90
  ldt/plugins/LDT_metforcing_pluginMod.F90
  ldt/plugins/LDT_param_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
  lis/configs/lis.config.adoc
  lis/make/default.cfg
  lis/metforcing/WRFAKdom/0Intro_WRF_AKdomain.txt
  lis/metforcing/WRFAKdom/WRF_AKdom_forcingMod.F90
  lis/metforcing/WRFAKdom/finalize_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/get_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/read_WRFAK_elev.F90
  lis/metforcing/WRFAKdom/read_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/readconfig_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/reset_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/timeinterp_WRF_AKdom.F90
  lis/metforcing/WRFoutv2/0Intro_WRFoutv2.txt
  lis/metforcing/WRFoutv2/WRFoutv2_forcingMod.F90
  lis/metforcing/WRFoutv2/finalize_WRFoutv2.F90
  lis/metforcing/WRFoutv2/get_WRFoutv2.F90
  lis/metforcing/WRFoutv2/read_WRFoutv2.F90
  lis/metforcing/WRFoutv2/read_WRFoutv2_elev.F90
  lis/metforcing/WRFoutv2/readconfig_WRFoutv2.F90
  lis/metforcing/WRFoutv2/reset_WRFoutv2.F90
  lis/metforcing/WRFoutv2/timeinterp_WRFoutv2.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
Labels: enhancement

#838 Add detail to LDT Users' Guide on DA source
  ldt/configs/ldt.config.adoc
Labels: Documentation, next patch release

#828 Added metadata to GeoTIFF files. Also changed layer numbering.
  lvt/utils/afwa/make_sm_geotiff.py
Labels: BugFix, HighPriority

#833 Updates/fixes to LVT USAFSIpost runmode for 557
  lvt/runmodes/USAFSIpost/LVT_USAFSIpostMod.F90
  lvt/utils/afwa/usafsipost/lvt.config.example
  lvt/utils/afwa/usafsipost/make_lvt_config_usafsipost.py
  lvt/utils/afwa/usafsipost/submit_lvt_usafsipost_discover.py
Labels: BugFix, HighPriority, LISF7.4

#853 Feature/ld tensrst upd
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_PRIV_rcMod.F90
  ldt/core/LDT_ensRstMod.F90
  ldt/core/LDT_ran2_gasdev.F90
Labels: enhancement

#860 Update documentation README
  docs/README.adoc
Labels: Documentation, enhancement

#856 Add new WRF Alaska forcing reader in LIS
  ldt/configs/ldt.config.adoc
  ldt/interp/compute_grid_coord_polar.F90
  ldt/make/Filepath
  ldt/metforcing/WRFAKdom/WRF_AKdom_forcingMod.F90
  ldt/metforcing/WRFAKdom/read_WRFAK_elev.F90
  ldt/metforcing/WRFAKdom/readconfig_WRF_AKdom.F90
  ldt/metforcing/WRFoutv2/WRFoutv2_forcingMod.F90
  ldt/plugins/LDT_metforcing_pluginMod.F90
  ldt/plugins/LDT_param_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
  lis/configs/lis.config.adoc
  lis/interp/compute_grid_coord_polar.F90
  lis/metforcing/WRFAKdom/0Intro_WRF_AKdomain.txt
  lis/metforcing/WRFAKdom/WRF_AKdom_forcingMod.F90
  lis/metforcing/WRFAKdom/finalize_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/get_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/read_WRFAK_elev.F90
  lis/metforcing/WRFAKdom/read_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/readconfig_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/reset_WRF_AKdom.F90
  lis/metforcing/WRFAKdom/timeinterp_WRF_AKdom.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
Labels: enhancement
