Repository NASA-LIS/LISF, pull requests merged in 2021-09, with the labels that each got.

#851 Numerous changes to LDT 7.3 to satisfy gfortran 11.1.0.
  ldt/DAobs/SMOPS/readSMOPSsmObs.F90
  ldt/core/LDT_gfracMod.F90
  ldt/core/LDT_gfrac_FTable.c
  ldt/core/LDT_laisaiMod.F90
  ldt/core/LDT_laisai_FTable.c
  ldt/params/FLAKE/FLAKE_parmsMod.F90
  ldt/params/FLAKE/read_FLake_lakedepth.F90
  ldt/params/LAISAI/read_CLSMF25_lai.F90
  ldt/params/gfrac/read_CLSMF25_gfrac.F90
  ldt/params/gfrac/read_SACHTET356_gfrac.F90
Labels: BugFix

#887 Fix for global domain HYMAP parameter setup where a boundary box of m…
  ldt/params/HYMAP/HYMAP_parmsMod.F90
Labels: BugFix

#892 Feature/hymap ensrst
  ldt/core/LDT_ensRstMod.F90
  ldt/params/HYMAP/read_HYMAP_baseflow_delay.F90
  ldt/params/HYMAP/read_HYMAP_baseflow_dwi_ratio.F90
  ldt/params/HYMAP/read_HYMAP_basin.F90
  ldt/params/HYMAP/read_HYMAP_basin_mask.F90
  ldt/params/HYMAP/read_HYMAP_drain_area.F90
  ldt/params/HYMAP/read_HYMAP_fld_height.F90
  ldt/params/HYMAP/read_HYMAP_fld_z.F90
  ldt/params/HYMAP/read_HYMAP_flow_dir_x.F90
  ldt/params/HYMAP/read_HYMAP_flow_dir_y.F90
  ldt/params/HYMAP/read_HYMAP_flow_type.F90
  ldt/params/HYMAP/read_HYMAP_grid_area.F90
  ldt/params/HYMAP/read_HYMAP_grid_dist.F90
  ldt/params/HYMAP/read_HYMAP_grid_elev.F90
  ldt/params/HYMAP/read_HYMAP_refq.F90
  ldt/params/HYMAP/read_HYMAP_river_height.F90
  ldt/params/HYMAP/read_HYMAP_river_length.F90
  ldt/params/HYMAP/read_HYMAP_river_width.F90
  ldt/params/HYMAP/read_HYMAP_river_z.F90
  ldt/params/HYMAP/read_HYMAP_runoff_delay.F90
  ldt/params/HYMAP/read_HYMAP_runoff_delaym.F90
  ldt/params/HYMAP/read_HYMAP_runoff_dwi_ratio.F90
  lis/interp/map_utils.F90
Labels: enhancement

#854 Numerous changes to LIS 7.3 to satisfy gfortran 11.1.0
  lis/core/LIS_alb_FTable.c
  lis/core/LIS_albedoMod.F90
  lis/core/LIS_emissMod.F90
  lis/core/LIS_emiss_FTable.c
  lis/core/LIS_laisai_FTable.c
  lis/core/LIS_roughness_FTable.c
  lis/core/LIS_vegDataMod.F90
  lis/make/default.cfg
  lis/params/emissivity/ALMIPII/read_ALMIPIIemiss.F90
  lis/surfacemodels/land/rdhm.3.5.6/sachtet/htet_fland1.f
  lis/surfacemodels/land/vic.4.1.1/vic411_f2t.F90
  lis/surfacemodels/land/vic.4.1.2.l/vic412_f2t.F90
Labels: BugFix

#855 Update LVT 7.3 to satisfy gfortran 11.1.0
  lvt/datastreams/SMOPS/readSMOPSsmObs.F90
Labels: BugFix

#865 Clean up LIS metforcing documentation
  docs/LIS_users_guide/intro.adoc
  docs/LIS_users_guide/obtain-source.adoc
  docs/LIS_users_guide/user_cfg_table.adoc
  lis/configs/lis.config.adoc
Labels: Documentation, Cleanup :broom:

#866 Clean up LIS metforcing reader testcases
  lis/testcases/metforcing/agrrad/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/agrrad/README
  lis/testcases/metforcing/agrrad/input.ctl
  lis/testcases/metforcing/agrrad/input_testcase.ctl
  lis/testcases/metforcing/agrrad/ldt.config
  lis/testcases/metforcing/agrrad/lis.config
  lis/testcases/metforcing/agrrad/output.ctl
  lis/testcases/metforcing/agrrad/testcase.ctl
  lis/testcases/metforcing/ceop/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/ceop/README
  lis/testcases/metforcing/ceop/lis.config
  lis/testcases/metforcing/ceop/output.ctl
  lis/testcases/metforcing/ceop/testcase.ctl
  lis/testcases/metforcing/ecmwfreanal/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/ecmwfreanal/README
  lis/testcases/metforcing/ecmwfreanal/input.ctl
  lis/testcases/metforcing/ecmwfreanal/input_testcase.ctl
  lis/testcases/metforcing/ecmwfreanal/ldt.config
  lis/testcases/metforcing/ecmwfreanal/lis.config
  lis/testcases/metforcing/ecmwfreanal/output.ctl
  lis/testcases/metforcing/ecmwfreanal/testcase.ctl
  lis/testcases/metforcing/geos/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/geos/README
  lis/testcases/metforcing/geos/input.ctl
  lis/testcases/metforcing/geos/input_testcase.ctl
  lis/testcases/metforcing/geos/ldt.config
  lis/testcases/metforcing/geos/lis.config
  lis/testcases/metforcing/geos/output.ctl
  lis/testcases/metforcing/geos/testcase.ctl
  lis/testcases/metforcing/merra-land/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/merra-land/README
  lis/testcases/metforcing/merra-land/input.ctl
  lis/testcases/metforcing/merra-land/input_testcase.ctl
  lis/testcases/metforcing/merra-land/ldt.config
  lis/testcases/metforcing/merra-land/lis.config
  lis/testcases/metforcing/merra-land/output.ctl
  lis/testcases/metforcing/merra-land/read_CONSTANT_lc.F90
  lis/testcases/metforcing/merra-land/testcase.ctl
  lis/testcases/metforcing/nldas1/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/nldas1/README
  lis/testcases/metforcing/nldas1/input.ctl
  lis/testcases/metforcing/nldas1/input_testcase.ctl
  lis/testcases/metforcing/nldas1/ldt.config
  lis/testcases/metforcing/nldas1/lis.config
  lis/testcases/metforcing/nldas1/output.ctl
  lis/testcases/metforcing/nldas1/testcase.ctl
  lis/testcases/metforcing/rhone/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/rhone/README
  lis/testcases/metforcing/rhone/lis.config
  lis/testcases/metforcing/rhone/output.ctl
  lis/testcases/metforcing/rhone/testcase.ctl
Labels: Cleanup :broom:

#900 Fix/lvtpost
  lvt/utils/afwa/cat_lvt_grib2.py
  lvt/utils/afwa/run_ncks.py
  lvt/utils/afwa/templates/METRICS.TBL
  lvt/utils/afwa/templates/TS_LOCATIONS.TXT
  lvt/utils/afwa/templates/lvt.config.template.jules50
  lvt/utils/afwa/templates/lvt.config.template.noah39
  lvt/utils/afwa/templates/lvt.config.template.noahmp401
  lvt/utils/afwa/templates/make_lvt_config_3hr_jules.py
  lvt/utils/afwa/templates/make_lvt_config_3hr_noah.py
  lvt/utils/afwa/templates/make_lvt_config_3hr_noahmp.py
Labels: HighPriority, LISF7.4

#897 Add PET code from Sujay to Noah-MP
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90
  lis/surfacemodels/land/noahmp.4.0.1/noahmp_driver_401.F90
  lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90
  lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
Labels: enhancement

#903 Edits to Working with GitHub document
  docs/working_with_github/working_with_github.adoc
Labels: Documentation
