Repository NASA-LIS/LISF, pull requests merged in 2021-02, with the labels that each got.

#706 Fix LVT Max and Min metric time series output
  lvt/core/LVT_statsDataMod.F90
  lvt/metrics/LVT_MEANMod.F90
  lvt/metrics/LVT_MaxMod.F90
  lvt/metrics/LVT_MinMod.F90
Labels: BugFix

#708 Update documentation regarding "Enable output statistics:"
  lis/configs/lis.config.adoc
Labels: Documentation

#715 Call LIS_lsm_DAmapTileSpaceToObsSpace instead of LIS_mapTileSpaceToObsSpace
  lis/surfacemodels/land/jules.5.x/da_snodep/jules5x_map_snodep.F90
  lis/surfacemodels/land/jules.5.x/da_usafsi/jules5x_map_usafsi.F90
Labels: BugFix

#718 Add GitHub Issue and Pull Request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/pull_request_template.md
Labels: enhancement

#722 Update LSM parameter file name for USAFSI
  ldt/USAFSI/ldt.config.sample
  ldt/configs/README_USAFSI
Labels: BugFix, HighPriority, LISF7.4

#724 Moved ldt.config files to for_discover directory.
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.jules50
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.jules50.cdf
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.jules50.ensemble
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.noah39
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.noah39.cdf
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.noah39.ensemble
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.noahmp401
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.noahmp401.cdf
  lis/configs/557WW-7.4-FOC/for_discover/ldt.config.global.noahmp401.ensemble
Labels: BugFix, HighPriority, LISF7.4

#727 Added support for FluxSat data in LVT
  lvt/configs/lvt.config.adoc
  lvt/datastreams/FluxSat_GPP/FluxSat_obsMod.F90
  lvt/datastreams/FluxSat_GPP/readFluxSatobs.F90
  lvt/make/Filepath
  lvt/plugins/LVT_datastream_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: enhancement
