Repository NASA-LIS/LISF, pull requests merged in 2021-11, with the labels that each got.

#921 Cleanup PR 777
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_irrigationMod.F90
  ldt/params/irrigation/read_USGSNative_irriggwratio.F90
  ldt/params/irrigation/setIrrigParmsFullnames.F90
  ldt/params/irrigation/set_irriggwratio_attribs.F90
  lis/irrigation/sprinkler/sprinkler_irrigationMod.F90
  lis/runmodes/smootherDA/smootherDA_runMod.F90
  lis/surfacemodels/land/noahmp.4.0.1/irrigation/noahmp401_getirrigationstates.F90
Labels: eis-freshwater, Cleanup :broom:

#925 Add SNODAS DA config documentation
  lis/configs/lis.config.adoc
Labels: Documentation, eis-freshwater

#927 Cleanup PR 845 and fix the write_UAsnowobs routine
  lis/optUE/type/paramestim/obs/UAsnow/UAsnow_obsMod.F90
  lis/optUE/type/paramestim/obs/UAsnow/read_UAsnowobs.F90
  lis/optUE/type/paramestim/obs/UAsnow/write_UAsnowobs.F90
  lis/testcases/paramest/ua_snow/NOAHMP_OUTPUT_LIST.TBL
  lis/testcases/paramest/ua_snow/lis.config
  lis/testcases/paramest/ua_snow/output.ctl
  lis/testcases/paramest/ua_snow/snod_obs_output.ctl
  lis/testcases/paramest/ua_snow/swe_obs_output.ctl
  lis/testcases/paramest/ua_snow/testcase.ctl
Labels: eis-freshwater, Cleanup :broom:

#930 Update LISF README document
  README.adoc
Labels: Documentation

#935 Fix several typos in S2S Python scripts.
  ldt/utils/usaf/s2s_ensrst/generate_ldtconfig_files_ensrst_nrt.py
  lvt/utils/usaf/s2spost/run_s2spost_9months.py
Labels: BugFix, HighPriority, LISF7.4

#931 Add Discover Quick Start Guide
  docs/README.adoc
  docs/discover_quick_start/discover_quick_start.adoc
Labels: Documentation
