Repository NASA-LIS/LISF, pull requests merged in 2022-01, with the labels that each got.

#963 Trim filenames when writing to log in a few metforcing readers
  lis/metforcing/HiMAT_GMU/read_HiMATGMU.F90
  lis/metforcing/cmorph/read_cmorph.F90
  lis/metforcing/gefs/get_gefs.F90
  lis/metforcing/mrms/read_mrms_grib.F90
  lis/metforcing/scan/read_scan.F90
  lis/metforcing/snotel/read_snotel.F90
  lis/metforcing/stg2/read_stg2.F90
  lis/metforcing/stg4/read_stg4.F90
Labels: BugFix

#964 Fix/julhr log
  lis/metforcing/usaf/AGRMET_getsfc.F90
  lis/metforcing/usaf/AGRMET_sfcalc.F90
  lis/metforcing/usaf/process_cloud_layers.F90
Labels: BugFix, HighPriority, LISF7.4

#967 Add workaround for Cray compilers
  lis/make/Makefile
Labels: HighPriority, LISF7.4

#966 Adds the H2 offline capability
  docs/LIS_users_guide/intro.adoc
  docs/LIS_users_guide/user_cfg_table.adoc
  lis/configs/lis.config.adoc
  lis/core/LIS_routingMod.F90
  lis/make/default.cfg
  lis/plugins/LIS_runoffdata_pluginMod.F90
  lis/routing/HYMAP2_router/HYMAP2_routing_run.F90
  lis/routing/HYMAP2_router/runoffdata/LISoutput/LISrunoffdataMod.F90
  lis/routing/HYMAP2_router/runoffdata/LISoutput/readLISrunoffdata.F90
Labels: enhancement

#968 USAFSI updates, including support for SST GRIB1 backup support
  ldt/USAFSI/LDT_usafsiMod.F90
  ldt/USAFSI/USAFSI_analysisMod.F90
  ldt/USAFSI/USAFSI_galwemMod.F90
  ldt/USAFSI/USAFSI_gofsMod.F90
  ldt/USAFSI/USAFSI_lisMod.F90
  ldt/USAFSI/USAFSI_run.F90
  ldt/USAFSI/USAFSI_utilMod.F90
  ldt/USAFSI/ldt.config.sample
  ldt/configs/ldt.config.adoc
  lvt/runmodes/USAFSIpost/LVT_USAFSIpostMod.F90
  lvt/utils/usaf/usafsipost/lvt.config.example
  lvt/utils/usaf/usafsipost/submit_lvt_usafsipost_discover.py
Labels: BugFix, HighPriority, LISF7.4, next patch release
