Repository NASA-LIS/LISF, pull requests merged in 2022-09, with the labels that each got.

#1207 Fixes to LIS log message directory lengths and reduced the NoahMP401 restart GECROS dimension
  lis/core/LIS_histDataMod.F90
  lis/core/LIS_metforcingMod.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_writerst.F90
Labels: HighPriority, LISF 557WW 7.5

#1111 New features in LIS for GVF DA and SMAP_E_OPL soil moisture DA
  lis/dataassim/obs/CDFS_GVF/CDFSgvf_Mod.F90
  lis/dataassim/obs/CDFS_GVF/read_CDFSgvf.F90
  lis/dataassim/obs/CDFS_GVF/write_CDFSgvfobs.F90
  lis/dataassim/obs/SMAP_E_OPLsm/SMAPEOPLsm_Mod.F90
  lis/dataassim/obs/SMAP_E_OPLsm/read_SMAPEOPLsm.F90
  lis/dataassim/obs/SMAP_E_OPLsm/write_SMAPEOPLsmobs.F90
  lis/dataassim/obs/VIIRS_GVF/VIIRSgvf_Mod.F90
  lis/dataassim/obs/VIIRS_GVF/read_VIIRSgvf.F90
  lis/dataassim/obs/VIIRS_GVF/write_VIIRSgvfobs.F90
  lis/make/default.cfg
  lis/plugins/LIS_DAobs_pluginMod.F90
  lis/plugins/LIS_lsmda_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
Labels: enhancement, HighPriority, NotReady, LISF 557WW 7.5

#1110 New features in LDT for GVF CDF generation and SMAP_E_OPL retrievals
  ldt/DAobs/CDFS_GVF/CDFS_GVF_obsMod.F90
  ldt/DAobs/CDFS_GVF/readCDFS_GVFObs.F90
  ldt/DAobs/GEOS_FP_TEFFobs/GEOSTEFF_obsMod.F90
  ldt/DAobs/GEOS_FP_TEFFobs/readGEOSTEFFObs.F90
  ldt/DAobs/LISlsmTEFFobs/LISlsmTEFF_obsMod.F90
  ldt/DAobs/LISlsmTEFFobs/readLISlsmTEFFObs.F90
  ldt/DAobs/SMAP_E_OPLsm/SMAPEOPL_SM_obsMod.F90
  ldt/DAobs/SMAP_E_OPLsm/readSMAPEOPL_SMObs.F90
  ldt/DAobs/VIIRS_GVF/VIIRS_GVF_obsMod.F90
  ldt/DAobs/VIIRS_GVF/readVIIRS_GVFObs.F90
  ldt/SMAP_E_OPL/ARFSSMRETRIEVAL.F90
  ldt/SMAP_E_OPL/DATADOMAIN.F90
  ldt/SMAP_E_OPL/FUNCTIONS.F90
  ldt/SMAP_E_OPL/LDT_smap_e_oplMod.F90
  ldt/SMAP_E_OPL/SMAPL1BTOL1C_ARFS.F90
  ldt/SMAP_E_OPL/TOOLSUBS.F90
  ldt/SMAP_E_OPL/VARIABLES.F90
  ldt/SMAP_E_OPL/algo_vpol_m.F90
  ldt/SMAP_E_OPL/invdist_l1b2arfs.F90
  ldt/SMAP_E_OPL/invdist_temp2smap.F90
  ldt/SMAP_E_OPL/mironov.f90
  ldt/SMAP_E_OPL/readLISTeff.f90
  ldt/SMAP_E_OPL/readLISsnow.f90
  ldt/SMAP_E_OPL/read_DailyTeffStats.F90
  ldt/SMAP_E_OPL/scale_teff.F90
  ldt/SMAP_E_OPL/varsio_m.F90
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_DAmetricsDataMod.F90
  ldt/core/LDT_DAmetricsMod.F90
  ldt/core/LDT_DAobsDataMod.F90
  ldt/core/LDT_DAobservationsMod.F90
  ldt/core/LDT_DApreprocMod.F90
  ldt/core/LDT_MuMod.F90
  ldt/core/LDT_PRIV_rcMod.F90
  ldt/core/LDT_SigmaMod.F90
  ldt/core/LDT_historyMod.F90
  ldt/core/LDT_timeMgrMod.F90
  ldt/make/Filepath
  ldt/plugins/LDT_DAobs_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
  ldt/plugins/LDT_runmode_pluginMod.F90
  ldt/runmodes/SMAP_E_OPL/LDT_init_smap_e_opl.F90
  ldt/runmodes/SMAP_E_OPL/LDT_run_smap_e_opl.F90
Labels: enhancement, NotReady
