Repository NASA-LIS/LISF, pull requests merged in 2022-05, with the labels that each got.

#1076 Extended/standardized file path lengths.
  ldt/USAFSI/LDT_usafsiMod.F90
  ldt/USAFSI/USAFSI_amsr2Mod.F90
  ldt/USAFSI/USAFSI_analysisMod.F90
  ldt/USAFSI/USAFSI_run.F90
  ldt/USAFSI/USAFSI_ssmisMod.F90
  ldt/USAFSI/USAFSI_utilMod.F90
  ldt/USAFSI/USAFSI_xcalgmiMod.F90
Labels: BugFix, HighPriority, LISF7.4

#1077 Fix/imerg read
  lis/metforcing/usaf/USAF_ImergHHMod.F90
  lis/metforcing/usaf/readagrmetpcpforcing.F90
Labels: BugFix, HighPriority, LISF7.4

#1078 Updated MPI decompositions to 576 by 1.
  lis/configs/557WW-7.4-FOC/NRT_GLOBAL/lis.config.global.jules50.ops
  lis/configs/557WW-7.4-FOC/NRT_GLOBAL/lis.config.global.jules50.ops.galwem10
  lis/configs/557WW-7.4-FOC/NRT_GLOBAL/lis.config.global.noah39.ops
  lis/configs/557WW-7.4-FOC/NRT_GLOBAL/lis.config.global.noah39.ops.galwem10
  lis/configs/557WW-7.4-FOC/NRT_GLOBAL/lis.config.global.noahmp401.ops
  lis/configs/557WW-7.4-FOC/NRT_GLOBAL/lis.config.global.noahmp401.ops.galwem10
Labels: BugFix, HighPriority, LISF7.4

#1087 Fix/lvt74 usafsipost endrun
  lvt/runmodes/USAFSIpost/LVT_run_USAFSIpost.F90
Labels: BugFix, HighPriority, LISF7.4

#1090 Extended dimID array for restarts to 11.
  lis/core/LIS_historyMod.F90
  lis/core/LIS_tbotAdjustMod.F90
  lis/surfacemodels/glacier/noahmp.3.9.1.1/noahmpglacier3911_writerst.F90
  lis/surfacemodels/lake/FLake.1.0/FLake1_writerst.F90
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_writerst.F90
  lis/surfacemodels/land/cable/cable_writerst.F90
  lis/surfacemodels/land/clsm.f2.5/clsmf25_writerst.F90
  lis/surfacemodels/land/hyssib/hyssib_writerst.F90
  lis/surfacemodels/land/jules.5.0/jules50_writerst.F90
  lis/surfacemodels/land/jules.5.1/jules51_writerst.F90
  lis/surfacemodels/land/jules.5.2/jules52_writerst.F90
  lis/surfacemodels/land/jules.5.3/jules53_writerst.F90
  lis/surfacemodels/land/jules.5.4/jules54_writerst.F90
  lis/surfacemodels/land/jules.5.x/jules5x_writerst.F90
  lis/surfacemodels/land/mosaic/mos_writerst.F90
  lis/surfacemodels/land/noah.2.7.1/noah271_writerst.F90
  lis/surfacemodels/land/noah.3.2/noah32_writerst.F90
  lis/surfacemodels/land/noah.3.3/noah33_writerst.F90
  lis/surfacemodels/land/noah.3.6/noah36_writerst.F90
  lis/surfacemodels/land/noah.3.9/noah39_writerst.F90
  lis/surfacemodels/land/noahmp.3.6/NoahMP36_writerst.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_writerst.F90
  lis/surfacemodels/land/rdhm.3.5.6/RDHM356_writerst.F90
  lis/surfacemodels/land/ruc.3.7/RUC37_writerst.F90
  lis/surfacemodels/land/vic.4.1.2.l/vic412_writerst.F90
Labels: BugFix, HighPriority, LISF7.4

#1096 Expand path length in a few more places
  lis/dataassim/obs/ANSA_SNWD/read_ANSASNWDsnow.F90
  lis/dataassim/obs/SSMI_SNWD/read_SSMISNWDsnow.F90
  lis/metforcing/gdasT1534/get_gdasT1534.F90
  lis/metforcing/genEnsFcst/get_genEnsFcst.F90
  lis/metforcing/gfs/get_gfs.F90
  lis/metforcing/gldas/get_gldas.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_writerst.F90
Labels: enhancement

#1093 Add total runoff output field in NoahMP401
  lis/configs/MODEL_OUTPUT_LIST.TBL.adoc
  lis/core/LIS_histDataMod.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90
  lis/testcases/surfacemodels/land/awral.6.0.0/AWRAL600_OUTPUT_LIST.TBL
Labels: enhancement

#1100 Changed filename convention for new USAFSI GRIB2 output.
  lvt/runmodes/USAFSIpost/LVT_USAFSIpostMod.F90
Labels: BugFix, HighPriority, LISF7.4

#1098 Silence err message when output dir already exists
  lis/core/LIS_create_subdirs.c
Labels: BugFix
