Repository NASA-LIS/LISF, pull requests merged in 2022-10, with the labels that each got.

#1026 Feature/crocus noah3.9
  lis/configs/lis.config.adoc
  lis/make/default.cfg
  lis/plugins/LIS_lsmrouting_pluginMod.F90
  lis/plugins/LIS_sublsm_pluginMod.F90
  lis/surfacemodels/land/noah.3.9/cplsubLSM/noah39_getCROCUSexport.F90
  lis/surfacemodels/land/noah.3.9/cplsubLSM/noah39_setCROCUSimport.F90
  lis/surfacemodels/land/noah.3.9/cplsubLSM/noah39_snow_update.F90
  lis/surfacemodels/land/noah.3.9/routing/noah39_getrunoffs_hymap2.F90
  lis/surfacemodels/land/noah.3.9/routing/noah39_getsws_hymap2.F90
Labels: enhancement, NotReady

#1218 Add support to specify RPC library
  ldt/arch/Config.pl
  lis/arch/Config.pl
  lvt/arch/Config.pl
Labels: HighPriority, LISF 557WW 7.4

#1221 Feature/retune gfs
  lis/utils/usaf/retune_bratseth/README
  lis/utils/usaf/retune_bratseth/cfgs/autotune.cfg
  lis/utils/usaf/retune_bratseth/scripts/autotune.py
Labels: enhancement, HighPriority, LISF 7.5

#1168 Adds the support for GRUN runoff
  lvt/configs/lvt.config.adoc
  lvt/datastreams/GRUNrunoff/GRUNrunoff_obsMod.F90
  lvt/datastreams/GRUNrunoff/readGRUNrunoffobs.F90
  lvt/make/Filepath
  lvt/plugins/LVT_datastream_pluginMod.F90
  lvt/plugins/LVT_pluginIndices.F90
Labels: enhancement

#1215 Add the LVT IMERG reader testcase
  lvt/testcases/datastreams/IMERG/METRICS.TBL
  lvt/testcases/datastreams/IMERG/README
  lvt/testcases/datastreams/IMERG/input.ctl
  lvt/testcases/datastreams/IMERG/lvt.config
  lvt/testcases/datastreams/IMERG/output.ctl
  lvt/testcases/datastreams/IMERG/testcase.ctl
Labels: BugFix

#1222 Set length of dimID to 11
  lis/surfacemodels/land/subLSM/crocus.8.1/Crocus81_writerst.F90
Labels: BugFix

#1224 Clean up build scripts
  lis/make/default.cfg
  lis/make/plugins.py
Labels: BugFix

#1225 Fixes for compiling with GNU and Cray compilers
  ldt/SMAP_E_OPL/ARFSSMRETRIEVAL.F90
  ldt/SMAP_E_OPL/LDT_smap_e_oplMod.F90
  lis/make/Makefile
Labels: HighPriority, NotReady, LISF 557WW 7.5

#1223 Address errors raised by GNU compilers
  ldt/make/Makefile
  lis/make/Makefile
  lvt/make/Makefile
Labels: BugFix

#1226 Fixes for compiling with Cray compilers
  ldt/DAobs/CDFS_GVF/CDFS_GVF_obsMod.F90
  ldt/DAobs/GEOS_FP_TEFFobs/GEOSTEFF_obsMod.F90
  ldt/DAobs/SMAP_E_OPLsm/SMAPEOPL_SM_obsMod.F90
  ldt/DAobs/VIIRS_GVF/VIIRS_GVF_obsMod.F90
  ldt/SMAP_E_OPL/readLISTeff.F90
  ldt/SMAP_E_OPL/readLISsnow.F90
  lis/dataassim/obs/CDFS_GVF/CDFSgvf_Mod.F90
  lis/dataassim/obs/VIIRS_GVF/VIIRSgvf_Mod.F90
Labels: HighPriority, LISF 557WW 7.5
