Repository NASA-LIS/LISF, pull requests merged in 2022-04, with the labels that each got.

#1044 Add support for compiling on IBM with GNU compilers
  ldt/arch/Config.pl
  lis/arch/Config.pl
Labels: enhancement

#1043 Fix/fault tolerance
  lis/dataassim/obs/SMAP_NRTsm/read_SMAPNRTsm.F90
  lis/dataassim/obs/SMOPS_ASCATsm/read_SMOPS_ASCATsm.F90
  lvt/utils/usaf/templates/submit_lvt_discover_3hr_noah.py
Labels: BugFix, HighPriority, LISF7.4

#1046 Customize "optimization level 2" flags for cray_cray architecture
  lis/arch/Config.pl
Labels: HighPriority, LISF7.4

#1042 Feature/li siodist
  lis/configs/lis.config.adoc
  lis/core/LIS_fileIOMod.F90
  lis/core/LIS_histDataMod.F90
  lis/core/LIS_historyMod.F90
  lis/core/LIS_surfaceModelMod.F90
  lvt/configs/lvt.config.adoc
  lvt/core/LVT_LISpostMod.F90
  lvt/core/LVT_fileIOMod.F90
  lvt/core/LVT_histDataMod.F90
  lvt/core/LVT_readConfig.F90
  lvt/make/Filepath
  lvt/plugins/LVT_pluginIndices.F90
  lvt/plugins/LVT_runmode_pluginMod.F90
  lvt/runmodes/LISpost/LVT_init_LISpost.F90
  lvt/runmodes/LISpost/LVT_run_LISpost.F90
Labels: enhancement

#1051 Fix/h2distout
  lis/core/LIS_fileIOMod.F90
  lis/core/LIS_historyMod.F90
  lis/routing/HYMAP2_router/runoffdata/LISoutput/readLISrunoffdata.F90
  lvt/core/LVT_LISpostMod.F90
Labels: BugFix

#1055 Added -fp0 flag for Cray compilers, for IEEE compliance.
  ldt/arch/Config.pl
Labels: BugFix, HighPriority, LISF7.4

#1058 Fix: enable LDT to compile without HDF5
  ldt/USAFSI/USAFSI_amsr2Mod.F90
  ldt/USAFSI/USAFSI_xcalgmiMod.F90
Labels: BugFix

#1062 Fixed FORMAT statement for reading presav files.
  lis/metforcing/usaf/AGRMET_processobs.F90
Labels: BugFix, HighPriority, LISF7.4

#1069 Updated Cray compiler flags for LIS with -O2.
  lis/arch/Config.pl
Labels: BugFix, HighPriority, LISF7.4

#1073 Correct LSM_finalize routines
  lis/surfacemodels/land/awral.6.0.0/AWRAL600_finalize.F90
  lis/surfacemodels/land/noahmp.3.6/NoahMP36_finalize.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_finalize.F90
  lis/surfacemodels/land/rdhm.3.5.6/RDHM356_finalize.F90
  lis/surfacemodels/land/ruc.3.7/RUC37_finalize.F90
Labels: HighPriority, LISF7.4
