Repository NASA-LIS/LISF, pull requests merged in 2022-02, with the labels that each got.

#982 Added missing METRICS.TBL.anomaly for SM anomaly calculations
  lvt/utils/usaf/templates/METRICS.TBL.anomaly
Labels: BugFix, HighPriority, LISF7.4

#973 Inherit max path length from ESMF
  lis/core/LIS_constantsMod.F90
Labels: enhancement

#983 Add kluge for compiling soil_htc_jls_mod.F90 on Cray systems
  lis/make/Makefile
Labels: BugFix, HighPriority, LISF7.4

#985 Feature/coamps forcing
  lis/configs/lis.config.adoc
  lis/make/default.cfg
  lis/metforcing/COAMPSout/COAMPSout_forcingMod.F90
  lis/metforcing/COAMPSout/finalize_COAMPSout.F90
  lis/metforcing/COAMPSout/get_COAMPSout.F90
  lis/metforcing/COAMPSout/read_COAMPSout.F90
  lis/metforcing/COAMPSout/readcrd_COAMPSout.F90
  lis/metforcing/COAMPSout/reset_COAMPSout.F90
  lis/metforcing/COAMPSout/timeinterp_COAMPSout.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
Labels: enhancement, metforcing
