Repository NASA-LIS/LISF, pull requests merged in 2022-11, with the labels that each got.

#1231 Add GALWEM (17km or 0.25deg) deterministic forecast reader
  lis/configs/lis.config.adoc
  lis/make/default.cfg
  lis/metforcing/galwem/finalize_galwem.F90
  lis/metforcing/galwem/galwem_forcingMod.F90
  lis/metforcing/galwem/get_galwem.F90
  lis/metforcing/galwem/read_galwem.F90
  lis/metforcing/galwem/readcrd_galwem.F90
  lis/metforcing/galwem/reset_galwem.F90
  lis/metforcing/galwem/timeinterp_galwem.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
Labels: enhancement, HighPriority, LISF 557WW 7.5

#1232 Add GALWEM-GE forecast reader
  lis/configs/lis.config.adoc
  lis/make/default.cfg
  lis/metforcing/galwem_ge/finalize_galwemge.F90
  lis/metforcing/galwem_ge/galwemge_forcingMod.F90
  lis/metforcing/galwem_ge/get_galwemge.F90
  lis/metforcing/galwem_ge/read_galwemge.F90
  lis/metforcing/galwem_ge/readcrd_galwemge.F90
  lis/metforcing/galwem_ge/reset_galwemge.F90
  lis/metforcing/galwem_ge/timeinterp_galwemge.F90
  lis/plugins/LIS_metforcing_pluginMod.F90
  lis/plugins/LIS_pluginIndices.F90
Labels: enhancement, HighPriority, LISF 557WW 7.5

#1235 Fixed name clash introduced by PR #1231.
  lis/metforcing/usaf/AGRMET_fldbld_galwem.F90
  lis/metforcing/usaf/AGRMET_fldbld_precip_galwem.F90
  lis/metforcing/usaf/USAF_bratsethMod.F90
  lis/testcases/metforcing/afwa-galwem/AGRMET_fldbld_galwem.F90
  lis/testcases/metforcing/afwa-galwem/AGRMET_fldbld_precip_galwem.F90
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1239 Updates to retune_bratseth scripts to boost pylint scores
  lis/utils/usaf/retune_bratseth/scripts/autotune.py
  lis/utils/usaf/retune_bratseth/scripts/create_blacklist.py
  lis/utils/usaf/retune_bratseth/scripts/customize_lis_config.py
  lis/utils/usaf/retune_bratseth/scripts/customize_procoba_nwp.py
  lis/utils/usaf/retune_bratseth/scripts/customize_procoba_sat.py
  lis/utils/usaf/retune_bratseth/scripts/fit_semivariogram.py
  lis/utils/usaf/retune_bratseth/scripts/plot_semivariogram.py
  lis/utils/usaf/retune_bratseth/scripts/rescale_sat_sigma2.py
  lis/utils/usaf/retune_bratseth/scripts/semivar.py
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1243 Corrections to LIS Users' Guide
  docs/LIS_users_guide/build.adoc
  docs/LIS_users_guide/user_cfg_table.adoc
  lis/configs/lis.config.adoc
Labels: HighPriority, LISF 557WW 7.5

#1244 Fix/lis75 mrf foc
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.jules50.hymap.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.jules50.hymap.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.jules50.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.jules50.rapid.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.noah39.hymap.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.noah39.hymap.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.noah39.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.noah39.rapid.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.noahmp401.hymap.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.noahmp401.hymap.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.noahmp401.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.global.noahmp401.rapid.galwem.0p25deg
Labels: HighPriority, LISF 557WW 7.5

#1245 Update revision history for Users' Guides for LISF 557WW 7.5.0 release
  docs/LDT_users_guide/LDT_users_guide.adoc
  docs/LDT_users_guide/revision_table.adoc
  docs/LISF_installation_guide/LISF_installation_guide.adoc
  docs/LISF_installation_guide/revision_table.adoc
  docs/LIS_users_guide/LIS_users_guide.adoc
  docs/LIS_users_guide/revision_table.adoc
  docs/LVT_users_guide/LVT_users_guide.adoc
  docs/LVT_users_guide/revision_table.adoc
Labels: HighPriority, LISF 557WW 7.5
