Repository NASA-LIS/LISF, pull requests merged in 2023-11, with the labels that each got.

#1442 Enable compiling LISF on Cray/SLES 15.4/PrgEnv 8.3.3 using Intel 2022.2.1 compilers
  env/narwhal/lisf_7.5_prgenv_intel_8.3.3
  ldt/arch/Config.pl
  lis/arch/Config.pl
  lis/make/Makefile
  lvt/arch/Config.pl
  lvt/core/LVT_create_subdirs.c
Labels: LISF 557WW 7.5

#1451 Updated NRT IMERG version to V06E.
  lis/configs/557WW-7.5-FOC/NRT_GLOBAL/lis.config.global.jules50.galwem17
  lis/configs/557WW-7.5-FOC/NRT_GLOBAL/lis.config.global.noah39.galwem17
  lis/configs/557WW-7.5-FOC/NRT_GLOBAL/lis.config.global.noahmp401.galwem17
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.jules50.hymap
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.jules50.rapid
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.hymap
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.rapid
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.hymap
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.rapid
  lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template
Labels: enhancement, LISF 557WW 7.5

#1453 Removed -Wpedantic debug flag for gfortran.
  ldt/arch/Config.pl
  lis/arch/Config.pl
  lvt/arch/Config.pl
Labels: BugFix

#1456 Fix cosphi roundoff error in spatial downscaling
  lis/core/LIS_spatialDownscalingMod.F90
Labels: eis-freshwater2

#1452 add distributed binary option for LIS_RST and LIS_DAPERT files
  lis/configs/lis.config.adoc
  lis/dataassim/perturb/gmaopert/gmaopert_Mod.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_readcrd.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_readrst.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_writerst.F90
Labels: eis-freshwater2

#1462 Update to S2S forecast processing script
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/process_forecast_data.py
  lis/utils/usaf/s2s/s2s_modules/s2splots/plot_anom_verify.py
Labels: BugFix, HighPriority, LISF 557WW 7.5
