Repository NASA-LIS/LISF, pull requests merged in 2023-06, with the labels that each got.

#1348 [GHI] Updated SM GeoTIFF filenames after consultation with 557WW and LCMC.
  lvt/utils/usaf/make_sm_geotiff.py
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1346 [GHI] Bug fixes for Medium Range Forecasts
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.hymap.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.hymap.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.rapid.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.hymap.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.hymap.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.rapid.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.hymap.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.hymap.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.rapid.galwem.0p25deg
  lis/configs/lis.config.adoc
  lis/core/LIS_fileIOMod.F90
  lis/core/LIS_readConfig.F90
  lis/metforcing/galwem/get_galwem.F90
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1337 Feature/s2s/lisf 557ww 7.5
  lis/utils/usaf/s2s/README_GHI-S2S_LIS7.5
  lis/utils/usaf/s2s/global_usaf_forc/README
  lis/utils/usaf/s2s/s2s_app/README_CFSv2_PATCHING
  lis/utils/usaf/s2s/s2s_app/check_cfsv2_bcsd.py
  lis/utils/usaf/s2s/s2s_app/check_disaggr_bcsd.py
  lis/utils/usaf/s2s/s2s_app/check_nmme_bcsd.py
  lis/utils/usaf/s2s/s2s_app/check_nmme_ncep.py
  lis/utils/usaf/s2s/s2s_app/download_nmme_hindcasts.sh
  lis/utils/usaf/s2s/s2s_app/nctool.py
  lis/utils/usaf/s2s/s2s_app/s2s_api.py
  lis/utils/usaf/s2s/s2s_app/s2s_config_global_fcast
  lis/utils/usaf/s2s/s2s_app/s2s_config_global_hcast
  lis/utils/usaf/s2s/s2s_app/s2s_hcst_preprocess.sh
  lis/utils/usaf/s2s/s2s_app/s2s_run.sh
  lis/utils/usaf/s2s/s2s_app/submit_hcast.sh
  lis/utils/usaf/s2s/s2s_app/wget_cfsv2_oper_ts_e2es.sh
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bias_correction_modulefast.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/calc_and_write_forecast_climatology.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/convert_forecast_data_to_netcdf.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/nmme_reorg_f.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/nmme_reorg_h.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/forecast_task_08.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/forecast_task_09.py
  lis/utils/usaf/s2s/s2s_modules/s2smetric/convert_s2s_anom_cf.py
  lis/utils/usaf/s2s/s2s_modules/s2smetric/metrics_library/convert_dyn_fcst_to_anom.py
  lis/utils/usaf/s2s/s2s_modules/s2smetric/metrics_library/convert_dyn_fcst_to_sanom.py
  lis/utils/usaf/s2s/s2s_modules/s2splots/plot_hybas.py
  lis/utils/usaf/s2s/s2s_modules/s2splots/plot_mena.py
  lis/utils/usaf/s2s/s2s_modules/s2splots/plot_s2smetrics.py
  lis/utils/usaf/s2s/s2s_modules/s2splots/plot_utils.py
  lis/utils/usaf/s2s/s2s_modules/s2spost/daily_s2spost_nc.py
  lis/utils/usaf/s2s/s2s_modules/s2spost/monthly_s2spost_nc.py
  lis/utils/usaf/s2s/s2s_modules/shared/utils.py
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1360 Address error raised by Cray compilers (CPE 23.02 / CCE 15.0.1)
  lis/dataassim/obs/SMAP_NRTsm/create_filelist.c
Labels: HighPriority, LISF 557WW 7.4

#1363 Update revision history for Users' Guides for LISF 557WW 7.5.5 release
  docs/LIS_users_guide/LIS_users_guide.adoc
  docs/LIS_users_guide/revision_table.adoc
Labels: HighPriority, LISF 557WW 7.5

#1367 Replaced call to LDT_endrun to avoid erroneous error code 1.
  ldt/USAFSI/USAFSI_run.F90
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1179 Changes the lat/lon fields in LIS output from 2d to 1d
  lis/configs/lis.config.adoc
  lis/core/LIS_PRIV_rcMod.F90
  lis/core/LIS_domainMod.F90
  lis/core/LIS_historyMod.F90
  lis/core/LIS_readConfig.F90
Labels: enhancement, help wanted

#1368 Disable AWRAL in user_557ww.cfg and user_ghis2s_557ww.cfg
  lis/make/user_557ww.cfg
  lis/make/user_ghis2s_557ww.cfg
Labels: HighPriority, LISF 557WW 7.5
