Repository NASA-LIS/LISF, pull requests merged in 2023-02, with the labels that each got.

#1186 Adds support for MCD12Q1 landcover
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_LMLCMod.F90
  ldt/core/LDT_paramProcMod.F90
  ldt/core/LDT_paramTileInputMod.F90
  ldt/params/landcover/read_MCD12Q1_lc.F90
  ldt/params/mask/read_maskfile.F90
  ldt/params/mask/read_maskfile_MCD12Q1.F90
  ldt/plugins/LDT_param_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
Labels: enhancement, NotReady

#1277 Add CECILL_C license for Crocus8.1
  lis/LICENSES/CNRS_CECILL_C_v1_Crocus8.1.txt
Labels: Documentation

#1278 Add Noah 3.2 and NoahMP 4.0.1
  lis/LICENSES/Noah_v2.7.1_v3.2_v3.3_v3.4_v3.6_v3.9.1_vMP_License.docx
  lis/LICENSES/Noah_v2.7.1_v3.2_v3.3_v3.6_v3.9.1_vMP_License.docx
Labels: Documentation

#1280 Correct dimensions of tmp_sfcheadrt, tmp_infxs1rt, and tmp_soldrain1rt
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90
Labels: BugFix

#1279 Fix compiling LIS/RAPID with Cray compilers
  env/discover/lisf_7_intel_2021.4.0_petsc
  lis/LICENSES/RAPID_License.txt
  lis/arch/Config.pl
  lis/routing/RAPID_router/RAPID_model_main.F90
Labels: BugFix, LISF 557WW 7.5
