Repository NASA-LIS/LISF, pull requests merged in 2024-11, with the labels that each got.

#1631 Update revision history for LDT Users' Guide for LISF 557WW 7.5.19 release
  docs/LDT_users_guide/LDT_users_guide.adoc
  docs/LDT_users_guide/revision_table.adoc
  ldt/configs/ldt.config.adoc
Labels: HighPriority, LISF 557WW 7.5

#1638 Add lislog messages when writing binary and distributed binary restarts
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_writerst.F90
Labels: BugFix, eis-freshwater2

#1636 Fix LDT MERRA-2 metforcing unnecessary memory allocation and logs
  ldt/metforcing/merra2/merra2_forcingMod.F90
  ldt/metforcing/merra2/readcrd_merra2.F90
Labels: BugFix

#1630 Add dynamic lapse rate usage and output to MERRA-2 metforcing
  lis/configs/MODEL_OUTPUT_LIST.TBL.adoc
  lis/configs/lis.config.adoc
  lis/core/LIS_constantsMod.F90
  lis/core/LIS_histDataMod.F90
  lis/core/LIS_metforcingMod.F90
  lis/core/LIS_spatialDownscalingMod.F90
  lis/core/LIS_tbotAdjustMod.F90
  lis/metforcing/merra2/get_merra2.F90
  lis/metforcing/merra2/merra2_forcingMod.F90
  lis/metforcing/merra2/read_merra2.F90
  lis/metforcing/merra2/readcrd_merra2.F90
Labels: enhancement, metforcing, eis-freshwater2

#1639 Add testcase files for dynamic lapse rate testcase
  lis/testcases/misc/dynamic_lapse_rate/MODEL_OUTPUT_LIST.TBL
  lis/testcases/misc/dynamic_lapse_rate/README
  lis/testcases/misc/dynamic_lapse_rate/input.ctl
  lis/testcases/misc/dynamic_lapse_rate/input_testcase.ctl
  lis/testcases/misc/dynamic_lapse_rate/ldt.config
  lis/testcases/misc/dynamic_lapse_rate/lis.config
  lis/testcases/misc/dynamic_lapse_rate/output.ctl
  lis/testcases/misc/dynamic_lapse_rate/testcase.ctl
Labels: eis-freshwater2

#1640 Update revision history for LISF Users Guides for LISF 557WW 7.6.0 release
  docs/LDT_users_guide/LDT_users_guide.adoc
  docs/LDT_users_guide/revision_table.adoc
  docs/LISF_installation_guide/LISF_installation_guide.adoc
  docs/LISF_installation_guide/additional_platforms.adoc
  docs/LISF_installation_guide/platforms.adoc
  docs/LISF_installation_guide/revision_table.adoc
  docs/LIS_users_guide/LIS_users_guide.adoc
  docs/LIS_users_guide/revision_table.adoc
  docs/LVT_users_guide/LVT_users_guide.adoc
  docs/LVT_users_guide/revision_table.adoc
Labels: LISF 557WW 7.6

#1643 Fix the bug in writing model output in 2D ensemble grid space #1627
  lis/core/LIS_historyMod.F90
Labels: bug
