Repository NASA-LIS/LISF, pull requests merged in 2024-09, with the labels that each got.

#1597 Added inverse exponential correlation function option.
  lis/configs/lis.config.adoc
  lis/metforcing/usaf/AGRMET_forcingMod.F90
  lis/metforcing/usaf/AGRMET_getsfc.F90
  lis/metforcing/usaf/AGRMET_processobs.F90
  lis/metforcing/usaf/AGRMET_sfcalc.F90
  lis/metforcing/usaf/USAF_GagesMod.F90
  lis/metforcing/usaf/USAF_ImergHHMod.F90
  lis/metforcing/usaf/USAF_bratsethMod.F90
  lis/metforcing/usaf/readagrmetpcpforcing.F90
  lis/metforcing/usaf/readcrd_agrmet.F90
Labels: enhancement, HighPriority, LISF 557WW 7.6

#1599 Improved end-of-file handling in LIS Bratseth scheme
  lis/metforcing/usaf/AGRMET_forcingMod.F90
  lis/metforcing/usaf/AGRMET_getsfc.F90
  lis/metforcing/usaf/USAF_PreobsReaderMod.F90
  lis/metforcing/usaf/readagrmetpcpforcing.F90
Labels: BugFix, HighPriority, LISF 557WW 7.6

#1602 Added new dupQC routine for future use.
  lis/metforcing/usaf/USAF_bratsethMod.F90
Labels: enhancement, HighPriority, LISF 557WW 7.6

#1605 Fix to argument size mismatches.
  lis/metforcing/usaf/AGRMET_storeobs.F90
  lis/metforcing/usaf/AGRMET_storeobs_offhour.F90
Labels: BugFix, HighPriority, LISF 557WW 7.6

#1607 Fixing Speckling Issues in MR
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_ensRstMod.F90
Labels: LISF 557WW 7.5

#1610 Increase length of lis_config_file to LIS_CONST_PATH_LEN
  lis/core/LIS_PRIV_rcMod.F90
  lis/core/LIS_process_cmd_args.F90
Labels: LISF 557WW 7.5

#1612 Correct interpolation in GEFS reader
  lis/metforcing/gefs/read_gefs_operational.F90
  lis/metforcing/gefs/timeinterp_gefs.F90
  lis/testcases/metforcing/gefs/MODEL_OUTPUT_LIST.TBL
  lis/testcases/metforcing/gefs/README
  lis/testcases/metforcing/gefs/input.ctl
  lis/testcases/metforcing/gefs/input_testcase.ctl
  lis/testcases/metforcing/gefs/ldt.config
  lis/testcases/metforcing/gefs/lis.config
  lis/testcases/metforcing/gefs/output.ctl
  lis/testcases/metforcing/gefs/testcase.ctl
Labels: BugFix
