Repository NASA-LIS/LISF, pull requests merged in 2024-06, with the labels that each got.

#1541 Bug fixes for LIS 7.5 NAFPA to handle unrecognized gage networks
  lis/metforcing/usaf/AGRMET_getpcpobs.F90
  lis/metforcing/usaf/AGRMET_storeobs.F90
  lis/metforcing/usaf/AGRMET_storeobs_offhour.F90
  lis/metforcing/usaf/USAF_bratsethMod.F90
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1551 Add new top-40cm layer soil moisture s2s metric
  lis/utils/usaf/s2s/s2s_app/s2s_config_global_fcast
  lis/utils/usaf/s2s/s2s_modules/s2smetric/convert_s2s_anom_cf.py
  lis/utils/usaf/s2s/s2s_modules/s2smetric/metrics_library/metricslib.py
Labels: HighPriority, LISF 557WW 7.5

#1544 Feature/ Resolved Issues and Added Tests to SMOPS Ver4 Reader
  lis/dataassim/obs/SMOPS_ASCATsm/SMOPS_ASCATsm_Mod.F90
  lis/dataassim/obs/SMOPS_ASCATsm/SMOPS_GRIB2_Tables_NESDIS.txt
  lis/dataassim/obs/SMOPS_ASCATsm/read_SMOPS_ASCATsm.F90
Labels: enhancement, HighPriority, LISF 557WW 7.5

#1549 New capability to use GALWEM or GFS radiation in AGRMET Ops mode.
  lis/configs/lis.config.adoc
  lis/metforcing/usaf/AGRMET_forcingMod.F90
  lis/metforcing/usaf/AGRMET_sfcalc.F90
  lis/metforcing/usaf/USAF_bratsethMod.F90
  lis/metforcing/usaf/USAF_fldbld_radflux.F90
  lis/metforcing/usaf/USAF_fldbld_radflux_galwem.F90
  lis/metforcing/usaf/USAF_fldbld_radflux_gfs.F90
  lis/metforcing/usaf/get_agrmet.F90
  lis/metforcing/usaf/readagrmetforcing.F90
  lis/metforcing/usaf/readcrd_agrmet.F90
  lis/surfacemodels/land/noah.3.9/noah39_readrst.F90
Labels: HighPriority, LISF 557WW 7.5

#1555 Code updates to handle when SMOPS ASCAT v4 file is missing.
  lis/dataassim/obs/SMOPS_ASCATsm/read_SMOPS_ASCATsm.F90
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1559 Fixed reset of alert_number.
  lis/metforcing/usaf/USAF_fldbld_radflux_galwem.F90
Labels: BugFix, HighPriority, LISF 557WW 7.5

#1558 Updated FOC settings for latest patches
  lis/configs/557WW-7.5-FOC/NRT_GLOBAL/lis.config.global.noah39.galwem17
  lis/configs/557WW-7.5-FOC/NRT_GLOBAL/lis.config.global.noahmp401.galwem17
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.rapid
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.rapid
  lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template
Labels: HighPriority, LISF 557WW 7.5

#1564 Add new AGRMET related runtime configuration settings
  lis/utils/usaf/s2s/for_discover/lis/lis.config.s2sglobal.noahmp401_12mem.hymap2.DARun
  lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template
  lis/utils/usaf/s2s/s2s_modules/lis_darun/template_files/lis.config_template.GLOBAL
Labels: HighPriority, LISF 557WW 7.5

#1565 Add missing AGRMET related runtime configuration
  lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template
Labels: HighPriority, LISF 557WW 7.5
