Repository NASA-LIS/LISF, pull requests merged in 2024-04, with the labels that each got.

#1512 Fixed RAPID routing model time step.
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.jules50.rapid.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noah39.rapid.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.rapid.galwem-ge
  lis/configs/557WW-7.5-FOC/MRF_GHI/lis.config.mr.noahmp401.rapid.galwem.0p25deg
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.jules50.rapid
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noah39.rapid
  lis/configs/557WW-7.5-FOC/NRT_STREAMFLOW/lis.config.nrt_streamflow.noahmp401.rapid
Labels: BugFix, HighPriority, LISF 557WW 7.5, LISF 557WW 7.6

#1516 [LDT] Fix bug slope value along the coastal area
  ldt/params/topo/read_MERIT1K_slope.F90
Labels: BugFix, HighPriority, LISF 557WW 7.6

#1469 Fix LIS Bratseth autotuning
  lis/metforcing/usaf/USAF_OBAMod.F90
  lis/metforcing/usaf/USAF_bratsethMod.F90
  lis/utils/usaf/retune_bratseth/cfgs/autotune.cfg
  lis/utils/usaf/retune_bratseth/cfgs/procOBA_NWP.gage.config
  lis/utils/usaf/retune_bratseth/cfgs/procOBA_NWP.rh2m.config
  lis/utils/usaf/retune_bratseth/cfgs/procOBA_NWP.spd10m.config
  lis/utils/usaf/retune_bratseth/cfgs/procOBA_NWP.t2m.config
  lis/utils/usaf/retune_bratseth/cfgs/procOBA_Sat.imerg.config
  lis/utils/usaf/retune_bratseth/scripts/autotune.py
  lis/utils/usaf/retune_bratseth/scripts/create_blacklist.py
  lis/utils/usaf/retune_bratseth/scripts/run_autotune_discover.sh
  lis/utils/usaf/retune_bratseth/scripts/run_autotune_hpc11.sh
Labels: BugFix, HighPriority, LISF 557WW 7.6

#1478 Fault tolerant version of GALWEM reader
  lis/core/LIS_coreMod.F90
  lis/metforcing/galwem/galwem_forcingMod.F90
  lis/metforcing/galwem/get_galwem.F90
  lis/metforcing/galwem/read_galwem.F90
Labels: BugFix, HighPriority, LISF 557WW 7.6

#1508 Removed unnecessary unit conversion in LIS SMAP_E_OPL reader
  lis/dataassim/obs/SMAP_E_OPLsm/read_SMAPEOPLsm.F90
Labels: BugFix, HighPriority, LISF 557WW 7.6

#1497 Add scripts for automating SMAP_E_OPL retrievals
  ldt/utils/usaf/SMAP_E_OPL/customize_ldt_smapeopl_config.py
  ldt/utils/usaf/SMAP_E_OPL/ldt.config.smapeopl.jules.tmpl
  ldt/utils/usaf/SMAP_E_OPL/ldt.config.smapeopl.noah.tmpl
  ldt/utils/usaf/SMAP_E_OPL/ldt.config.smapeopl.noahmp.tmpl
  ldt/utils/usaf/SMAP_E_OPL/run_smap_e_opl_discover.sh
Labels: enhancement, HighPriority, LISF 557WW 7.6

#1529 Bug fixes to ensure files are closed and file unit numbers released.
  lis/metforcing/usaf/USAF_GagesMod.F90
  lis/metforcing/usaf/USAF_PreobsReaderMod.F90
Labels: BugFix, HighPriority, LISF 557WW 7.6
