Repository NASA-LIS/LISF, pull requests merged in 2024-12, with the labels that each got.

#1646 Updated MR Bridge FOC files
  lis/configs/557WW-7.6-FOC/MR/ldt_bridge/ldt.config.bridge.noah39.76
  lis/configs/557WW-7.6-FOC/MR/ldt_bridge/ldt.config.bridge.noahmp401.76
Labels: BugFix, LISF 557WW 7.6

#1647 Fix bug slope value along the coastal area
  ldt/params/topo/read_MERIT1K_slope.F90
Labels: eis-freshwater2

#1650 Changes to support WIGOS in autotuning.
  lis/metforcing/usaf/USAF_OBAMod.F90
  lis/utils/usaf/retune_bratseth/scripts/create_blacklist.py
  lis/utils/usaf/retune_bratseth/src/USAF_ReportsMod.F90
  lis/utils/usaf/retune_bratseth/src/USAF_sharedMod.F90
  lis/utils/usaf/retune_bratseth/src/procOBA_NWP.F90
  lis/utils/usaf/retune_bratseth/src/procOBA_Sat.F90
Labels: BugFix, LISF 557WW 7.6

#1659 Updated codes for ESPC-D file (SST)
  ldt/USAFSI/USAFSI_espcdMod.F90
  ldt/USAFSI/USAFSI_run.F90
Labels: LISF 557WW 7.5

#1663 Update to S2S run - group jobs option
  lis/utils/usaf/s2s/s2s_app/s2s_run.sh
Labels: LISF 557WW 7.5

#1661 Add MERRA-2 dynamic lapse rate double-sided cutoff
  lis/configs/lis.config.adoc
  lis/metforcing/merra2/get_merra2.F90
  lis/metforcing/merra2/merra2_forcingMod.F90
  lis/metforcing/merra2/readcrd_merra2.F90
Labels: enhancement, metforcing, eis-freshwater2

#1662 Fix for soil texture force-fill exclusion in LDT
  ldt/configs/ldt.config.adoc
  ldt/core/LDT_soilsMod.F90
  ldt/params/topo/read_SRTM_Native_aspect.F90
  ldt/params/topo/read_SRTM_Native_elev.F90
  ldt/params/topo/read_SRTM_Native_slope.F90
Labels: BugFix, LISF 7.5
