Repository NASA-LIS/LISF, pull requests merged in 2024-07, with the labels that each got.

#1538 Updated LIS to read ASCAT Metop-B and C from SMOPS V4
  lis/dataassim/obs/SMOPS_ASCATsm/SMOPS_ASCATsm_Mod.F90
  lis/dataassim/obs/SMOPS_ASCATsm/SMOPS_GRIB2_Tables_NESDIS.txt
  lis/dataassim/obs/SMOPS_ASCATsm/read_SMOPS_ASCATsm.F90
Labels: NotReady, Draft, DO NOT MERGE

#1571 Add GLASS LAI and GLASS Albedo configs to the LIS Users' Guide.
  docs/LIS_users_guide/obtain-source.adoc
  lis/configs/lis.config.adoc
Labels: Documentation

#1545 Patch to gracefully handle unrecognized gage networks
  lis/configs/lis.config.adoc
  lis/metforcing/usaf/AGRMET_forcingMod.F90
  lis/metforcing/usaf/AGRMET_getpcpobs.F90
  lis/metforcing/usaf/AGRMET_storeobs.F90
  lis/metforcing/usaf/AGRMET_storeobs_offhour.F90
  lis/metforcing/usaf/USAF_PreobsReaderMod.F90
  lis/metforcing/usaf/USAF_bratsethMod.F90
  lis/metforcing/usaf/USAF_getpcpobs.F90
  lis/metforcing/usaf/readcrd_agrmet.F90
Labels: BugFix, HighPriority, LISF 557WW 7.6

#1582 Change start date of SMOPS ASCAT v4 data to match our archive.
  lis/dataassim/obs/SMOPS_ASCATsm/SMOPS_ASCATsm_Mod.F90
  lis/dataassim/obs/SMOPS_ASCATsm/read_SMOPS_ASCATsm.F90
Labels: bug, LowPriority, LISF 557WW 7.5
