Repository NASA-LIS/LISF, pull requests merged in 2024-10, with the labels that each got.

#1622 Revised alert and abort message files for USAFSI
  ldt/USAFSI/USAFSI_amsr2Mod.F90
  ldt/USAFSI/USAFSI_analysisMod.F90
  ldt/USAFSI/USAFSI_espcdMod.F90
  ldt/USAFSI/USAFSI_run.F90
  ldt/USAFSI/USAFSI_ssmisMod.F90
  ldt/USAFSI/USAFSI_utilMod.F90
  ldt/USAFSI/USAFSI_xcalgmiMod.F90
Labels: BugFix, HighPriority, LISF 557WW 7.6

#1623 Revised alert and abort message files for USAFSI
  ldt/USAFSI/USAFSI_amsr2Mod.F90
  ldt/USAFSI/USAFSI_analysisMod.F90
  ldt/USAFSI/USAFSI_espcdMod.F90
  ldt/USAFSI/USAFSI_run.F90
  ldt/USAFSI/USAFSI_ssmisMod.F90
  ldt/USAFSI/USAFSI_utilMod.F90
  ldt/USAFSI/USAFSI_xcalgmiMod.F90
Labels: HighPriority, LISF 557WW 7.5

#1624 Fixed uninitialized variable in Noah-MP401 irrigation module
  lis/surfacemodels/land/noahmp.4.0.1/irrigation/noahmp401_getirrigationstates.F90
Labels: BugFix, LISF 7.5

#1626 Fix/update s2s nmme
  lis/utils/usaf/s2s/README_GHI-S2S_LIS7.5
  lis/utils/usaf/s2s/for_discover/ldt/ldt.config_noahmp401_nmme_canesm5_202408
  lis/utils/usaf/s2s/for_discover/ldt/ldt.config_noahmp401_nmme_cesm1_202408
  lis/utils/usaf/s2s/for_discover/ldt/ldt.config_noahmp401_nmme_gnemo52_202408
  lis/utils/usaf/s2s/for_discover/lis/lis.config.s2sglobal.noahmp401.hymap2.da_ics_forecast_CESM1_202408
  lis/utils/usaf/s2s/for_discover/lis/lis.config.s2sglobal.noahmp401.hymap2.da_ics_forecast_CanESM5_202408
  lis/utils/usaf/s2s/for_discover/lis/lis.config.s2sglobal.noahmp401.hymap2.da_ics_forecast_GNEMO52_202408
  lis/utils/usaf/s2s/for_discover/lis/lis.config.s2sglobal.noahmp401_12mem.hymap2.DARun
  lis/utils/usaf/s2s/global_usaf_forc/input/lis.config.template
  lis/utils/usaf/s2s/s2s_app/check_nmme_bcsd.py
  lis/utils/usaf/s2s/s2s_app/convert_tiff.py
  lis/utils/usaf/s2s/s2s_app/download_nmme_hindcasts.sh
  lis/utils/usaf/s2s/s2s_app/download_nmme_precip.sh
  lis/utils/usaf/s2s/s2s_app/s2s_config_global_fcast
  lis/utils/usaf/s2s/s2s_app/s2s_config_global_hcast
  lis/utils/usaf/s2s/s2s_app/s2s_hcst_preprocess.sh
  lis/utils/usaf/s2s/s2s_app/s2s_run.sh
  lis/utils/usaf/s2s/s2s_app/submit_hcast.sh
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bias_correction_modulefast.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/bias_correction_nmme_modulefast.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/convert_forecast_data_to_netcdf.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/nmme_reorg_f.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/nmme_reorg_h.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/bcsd_library/process_forecast_data.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/check_preprocess_forecast_files.py
  lis/utils/usaf/s2s/s2s_modules/bcsd_fcst/forecast_task_01.py
  lis/utils/usaf/s2s/s2s_modules/ldt_ics/generate_ldtconfig_files_ensrst_nrt.py
  lis/utils/usaf/s2s/s2s_modules/lis_darun/template_files/lis.config_template.GLOBAL
  lis/utils/usaf/s2s/s2s_modules/lis_fcst/generate_lis_config_scriptfiles_fcst.py
  lis/utils/usaf/s2s/s2s_modules/s2splots/plot_utils.py
  lis/utils/usaf/s2s/s2s_modules/s2splots/plot_weekly_anom.py
  lis/utils/usaf/s2s/s2s_modules/shared/utils.py
Labels: HighPriority, LISF 557WW 7.5
