Repository NASA-LIS/LISF, pull requests merged in 2025-07, with the labels that each got.

#1709 Updated the GALWEM-GE reader
  lis/configs/lis.config.adoc
  lis/metforcing/galwem_ge/galwemge_forcingMod.F90
  lis/metforcing/galwem_ge/get_cdf_params.F90
  lis/metforcing/galwem_ge/get_galwemge.F90
  lis/metforcing/galwem_ge/read_galwemge.F90
  lis/metforcing/galwem_ge/readcrd_galwemge.F90
  lis/metforcing/galwem_ge/timeinterp_galwemge.F90
  lis/utils/usaf/galwem_ge/fault_tolerance_galwem_ge.py
  lis/utils/usaf/galwem_ge/template/lis.config.mr.noah39.rapid.template
  lis/utils/usaf/galwem_ge/template/lis.config.mr.noahmp401.rapid.template
  lis/utils/usaf/galwem_ge/update_lis_config.py
Labels: enhancement, HighPriority, Draft, LISF 557WW 7.6

#1726 Changed default deflate level to 1.
  ldt/arch/Config.pl
  lis/arch/Config.pl
  lvt/arch/Config.pl
Labels: enhancement, HighPriority, LISF 557WW 7.6

#1728 Updated Intel compiler flags for strict checks.
  ldt/arch/Config.pl
  lis/arch/Config.pl
  lvt/arch/Config.pl
Labels: BugFix, HighPriority, LISF 557WW 7.6
