Repository NASA-LIS/LISF, pull requests merged in 2025-01, with the labels that each got.

#1672 Amended FOC files for option to switch to SMAP L2 DA.
  lis/configs/557WW-7.6-FOC/NRT/lis.config.foc.nrt.jules50.76
  lis/configs/557WW-7.6-FOC/NRT/lis.config.foc.nrt.noah39.76
  lis/configs/557WW-7.6-FOC/NRT/lis.config.foc.nrt.noahmp401.76
  lis/configs/557WW-7.6-FOC/NRT_STREAMFLOW/lis.config.foc.nrt_streamflow.noah39.hymap.76
  lis/configs/557WW-7.6-FOC/NRT_STREAMFLOW/lis.config.foc.nrt_streamflow.noah39.rapid.76
  lis/configs/557WW-7.6-FOC/NRT_STREAMFLOW/lis.config.foc.nrt_streamflow.noahmp401.hymap.76
  lis/configs/557WW-7.6-FOC/NRT_STREAMFLOW/lis.config.foc.nrt_streamflow.noahmp401.rapid.76
Labels: LISF 557WW 7.6

#1671 Fix template LSM crash if Rainf is not selected as forcing variable
  lis/surfacemodels/land/template/template_f2t.F90
Labels: BugFix, LISF 7.5

#1674 Rewrote defineNETCDFheaderVar in lis/core/LIS_historyMod.F90
  lis/core/LIS_historyMod.F90
Labels: BugFix, HighPriority, Cleanup :broom:, LISF 557WW 7.6

#1645 NUOPC Cap Improvements
  lis/runmodes/nuopc_cpl_mode/Doxyfile
  lis/runmodes/nuopc_cpl_mode/LIS_ESMF_Extensions.F90
  lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_Cap.F90
  lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_DataCopy.F90
  lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_Flags.F90
  lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_Gluecode.F90
  lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_Macros.h
  lis/runmodes/nuopc_cpl_mode/Makefile
  lis/runmodes/nuopc_cpl_mode/README.md
  lis/runmodes/nuopc_cpl_mode/docs/1_users_guide.md
  lis/runmodes/nuopc_cpl_mode/docs/2_developers_guide.md
Labels: enhancement, Documentation, Cleanup :broom:
