Repository NASA-LIS/LISF, pull requests merged in 2025-05, with the labels that each got.

#1687 Add NoahMP groundwater coupling through NUOPC Cap
  lis/arch/Config.pl
  lis/core/LIS_coreMod.F90
  lis/core/LIS_histDataMod.F90
  lis/core/LIS_runmode_FTable.c
  lis/plugins/LIS_lsmcpl_pluginMod.F90
  lis/plugins/LIS_runmode_pluginMod.F90
  lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_Cap.F90
  lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_DataCopy.F90
  lis/runmodes/nuopc_cpl_mode/LIS_NUOPC_Gluecode.F90
  lis/runmodes/nuopc_cpl_mode/Makefile
  lis/runmodes/retrospective/retrospective_runMod.F90
  lis/runmodes/smootherDA/smootherDA_runMod.F90
  lis/runmodes/wrf_cpl_mode/LISWRFGridCompMod.F90
  lis/runmodes/wrf_cpl_mode/LISWRFexport_module.F90
  lis/surfacemodels/land/noah.3.3/cpl_wrf_noesmf/noah33_setwrfexport.F90
  lis/surfacemodels/land/noah.3.3/module_sf_noah33lsm.F90
  lis/surfacemodels/land/noah.3.3/noah33_lsmMod.F90
  lis/surfacemodels/land/noah.3.3/noah33_main.F90
  lis/surfacemodels/land/noah.3.3/noah33_module.F90
  lis/surfacemodels/land/noahmp.3.6/NoahMP36_lsmMod.F90
  lis/surfacemodels/land/noahmp.3.6/NoahMP36_main.F90
  lis/surfacemodels/land/noahmp.3.6/NoahMP36_module.F90
  lis/surfacemodels/land/noahmp.3.6/cpl_wrf_noesmf/noahMP36_setwrfexport.F90
  lis/surfacemodels/land/noahmp.3.6/module_sf_noahmplsm_36.F90
  lis/surfacemodels/land/noahmp.3.6/noahmp_driver_36.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_lsmMod.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_main.F90
  lis/surfacemodels/land/noahmp.4.0.1/NoahMP401_module.F90
  lis/surfacemodels/land/noahmp.4.0.1/cpl_wrf_noesmf/noahMP401_setwrfexport.F90
  lis/surfacemodels/land/noahmp.4.0.1/noahmp_driver_401.F90
  lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmpdrv_401.F90
  lis/surfacemodels/land/noahmp.4.0.1/phys/module_sf_noahmplsm_401.F90
Labels: enhancement, HighPriority

#1702 Support full ensemble mode for RAPID
  ldt/core/LDT_ensRstMod.F90
  ldt/make/Filepath
  ldt/params/RAPID/RAPID_parmsMod.F90
  ldt/plugins/LDT_param_pluginMod.F90
  ldt/plugins/LDT_pluginIndices.F90
  ldt/testcases/Ensemble_restart_RAPID/README
  ldt/testcases/Ensemble_restart_RAPID/ldt.config
  lis/configs/lis.config.adoc
  lis/routing/RAPID_router/RAPID_model_main.F90
  lis/routing/RAPID_router/RAPID_routingMod.F90
  lis/routing/RAPID_router/RAPID_routing_output.F90
  lis/routing/RAPID_router/RAPID_routing_readrst.F90
  lis/routing/RAPID_router/RAPID_routing_run.F90
  lis/routing/RAPID_router/RAPID_routing_writerst.F90
  lis/testcases/routing/RAPID_ensemble/MODEL_OUTPUT_LIST.TBL
  lis/testcases/routing/RAPID_ensemble/README
  lis/testcases/routing/RAPID_ensemble/input.ctl
  lis/testcases/routing/RAPID_ensemble/input_testcase.ctl
  lis/testcases/routing/RAPID_ensemble/ldt.config
  lis/testcases/routing/RAPID_ensemble/lis.config
Labels: LISF 557WW 7.6

#1707 Patch to increase number of screen-level observations used in analysis.
  lis/metforcing/usaf/AGRMET_getsfc.F90
Labels: enhancement, HighPriority, LISF 557WW 7.6
